- src/libs/ck-libs/ampi/ampi.h
- src/libs/ck-libs/ampi/ampi_noimpl.C
- src/libs/ck-libs/ampi/ampiimpl.h
*Original date: 2019-05-08 17:01:48*
*Original PR: https://charm.cs.illinois.edu/gerrit/5182*
---
Change-Id: If77c986d2c3d66f9f9995a78a1099404d169017b
> AMPI: Fix PMPI linking errors

- doc/charm++/manual.rst
Change-Id: I99592f6f6614cfc05f2b20ee7659659830591164
> doc: fix malformed hyperlink target

- src/ck-core/ckarray.C
*Original date: 2019-05-07 16:24:02*
*Original PR: https://charm.cs.illinois.edu/gerrit/5165*
---
Change-Id: I817eb1f728bb13255e59cd48c367edabc714d460
> Add assertion to CkArray::recvBroadcast deliver loop

- src/conv-core/cputopology.C
> Cleanup #1907: Reimplement CmiNumCores using hwloc

- src/arch/util/machine-smp.C
Necessary code was entirely missing from the Windows version of the
call_startfn function.
> Resolve hang in user-driven-interop on Windows

- src/util/charmrun-src/charmrun.C
This is necessary to support interactive charm4py sessions when
using charmrun+ssh.
> charmrun: Add ++interactive option for tty ssh connection to process 0

- doc/charm++/manual.rst
> Documentation #2077: RAJA interoperability

- src/arch/cuda/hybridAPI/hapi.h
> Add optional parameter for freeing CkCallback in GPUManager WorkRequest

- src/ck-core/ckrdma.C
Previously, buffers were de-registered after completion of RDMA transfers.
However, when buffers are declared with CK_BUFFER_REG (and PREREG for verbs
and ucx), it is required to de-register these buffers after the completion
of the memcpy and CMA transfers to avoid leaking of pinned memory.
> ZC Bcast Post API: Deregister buffers after completion of memcpy and CMA transfers

- src/conv-core/conv-conds.C
This added a dependency from Converse into Charm++, which breaks
certain compilation modes.
This reverts commit 2b7d9a7e0f8d9643e602160dfae44b46773e3573.
> Revert "Feature #1436: Trace CcdCallFnAfter() causality (#2296)"

- src/arch/common/conv-mach-common.h
- src/arch/gni/machine-onesided.C
- src/arch/gni/machine.C
- src/arch/ofi/machine-onesided.C
- src/arch/verbs/machine-ibverbs.C
- src/arch/verbs/machine-onesided.C
- src/ck-core/ckrdma.C
- src/ck-core/ckrdma.h
Change-Id: I34f932dd7ee104d703483a77818ca261719982e2
> ZC Direct API: De-register registered buffers and respect de-reg modes

- src/ck-core/ckrdma.C
Before this fix, ZC Bcast API was incorrectly reporting ack handling
when the first memcpy operation was complete. With this fix, the bcast ack
handler is called when all the memcpy operations are complete.
> ZC Bcast API: Invoke Bcast Ack Handler when all memcpy ops are complete

- src/arch/shmem/machine.C
- src/arch/sim/machine.C
I don't have access to Cray to test shmem. I tried to test the sim build, but compilation was broken for many other reasons it looked like.
> Add WNB definition to other missing layers

- .travis.yml
These builds are now done in circleci.
> Travis: remove Netlrts-linux builds

- src/xlat-i/sdag/constructs/Forall.C
> Fix SDAG forall code generation

- src/libs/ck-libs/ampi/ddt.C
- src/libs/ck-libs/ampi/ddt.h
- implement type map printing
- dump type map and other options on creating each type
> DDT: implement better debugging

- src/arch/util/machine-smp.C
Fixes #2388 
Also fixes the separate contention issue mentioned in the reverted patch
> Revert C++11 barrier implementation

- src/libs/Makefile
> cleanup: remove another vestige of other libs

- tests/converse/Makefile
- tests/converse/megacon/Makefile
Same pattern as for charm tests in PR #2327
> Add smptest target for converse tests

- src/arch/common/special.sh
- src/libs/ck-libs/ampi/Makefile
- src/libs/ck-libs/ampi/ampiCC
- src/scripts/charmc
Fixes #2427. Followup from #2062/#2121. See also #2459. Only lightly tested.
> AMPI+CUDA: fix build

- src/libs/ck-libs/ampi/ampiCC
- src/scripts/charmc
> AMPI+CUDA: fix spurious error messages

- examples/charm++/cuda/busywait/Makefile
- examples/charm++/cuda/hello/Makefile
- examples/charm++/cuda/matmul/Makefile
- examples/charm++/cuda/mempool/Makefile
- examples/charm++/cuda/qdtest/Makefile
- examples/charm++/cuda/stencil2d/Makefile
- examples/charm++/cuda/vecadd/Makefile
- src/arch/common/conv-mach-cuda.sh
- src/arch/common/special.sh
- src/libs/ck-libs/ampi/Makefile
- src/libs/ck-libs/ampi/ampiCC
- src/scripts/charmc
Reverts #2462 #2460 #2121 .
Manually tested on talent.
> Revert+fix cuda linking

- .gitignore
also sort ignored dirs alphabetically
> cleanup: git ignore ucx build dir

- src/libs/ck-libs/ampi/ampi.C
Also fix AMPI_NODE_LOCAL_IMPL to do what it intends to do.
> AMPI #2436: fix bug in ampi::requestPut for contiguous datatypes

- benchmarks/Makefile
- examples/Makefile
- examples/bigsim/Makefile
- tests/Makefile
> Workaround #2489: Don't run Converse tests when CUDA is enabled

- src/scripts/configure.ac
> remove '<<<' bashism from configure

- src/util/charmrun-src/charmrun.C
This cleans up a few minor leaks in argument parsing so that
address sanitizer will at least run cleanly when ++local is used.
> cleanup: Address sanitizer reports leaks for charmrun

- CITATION.cff
Author listing in the Zenodo entry follows Zenodo's own list (minus putting Sanjay first).
> citation.cff: add BibTeX entries as comments

- src/conv-core/convcore.C
> Fix backtrace and remove debug print

- src/scripts/Makefile
> Fix OPTS when rebuilding libmemory and libthreads from tmp

- src/arch/cuda/hybridAPI/hapi_impl.cpp
> Remove duplicate lock in HAPI stream creation

- src/libs/ck-libs/ampi/CMakeLists.txt
> cmake: add conv-static dependency to romio

- doc/charm++/manual.rst
- src/ck-core/ckarray.C
- src/ck-core/ckarray.h
- src/ck-core/cklocation.C
- src/ck-core/ckmigratable.h
> CkAbort: allow format strings in CkArray, CkMigratable

- src/scripts/testrun
> testrun: print time

- examples/charm++/wave2d/wave2d.C
- examples/charm++/wave2d/wave2d.ci
- src/arch/netlrts/machine.C
- src/ck-core/ckmemcheckpoint.C
- src/ck-core/ckmemcheckpoint.h
- src/ck-ldb/manager.C
- src/util/charmrun-src/charmrun.C
Please **rebase and merge** when approved.
> Cleanups to FT codepaths

- src/arch/cuda/hybridAPI/hapi_impl.cpp
> HAPI: Remove redundant CMK_MULTICORE, replace printf with CmiPrintf

- src/util/charmrun-src/charmrun.C
Tested on the Adaptivity Demo cluster.
> Charmrun: Fix ++ssh-display without ++batch

- src/scripts/charmc
Fixes #2617.
These options are documented here: https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html
> charmc #2617: support -isystem -iquote -idirafter

- src/scripts/charmc
> charmc #2617: pass through rsp files

- src/conv-core/converse.h
> Fix missing CmiInCommThread

- src/ck-ldb/LBDatabase.C
> LBDB: fix CMK_LBDB_ON #ifdef

- src/ck-ldb/LBDatabase.C
- src/conv-core/convcore.C
Followup from #2528, #2540.
See also #2666.
> LBDB: fix more undefined symbols

- src/conv-core/cpuaffinity.C
When setting CPU affinity, node and PE ranks on a host were originally
set non-deterministically in arrival order and then sorted to get into
order in quadratic time. Instead, wait for all PEs to check in and
then set their ranks directly.
> Cleanup: Enumerate host ranks directly when setting affinity

- src/libs/ck-libs/ampi/ampiimpl.h
This avoids heap allocations when managing the pool.
> AmpiMsgPool: Use constant length vector instead of forward_list

- examples/bigsim/emulator/littleMD/Handlers.C
- examples/charm++/piArray/pgm.C
- src/arch/mpi-win64/conv-mach.sh
- src/arch/multicore-win64/conv-mach.sh
- src/arch/netlrts-win-x86_64/conv-mach.sh
- src/arch/win/unix2nt_cc
- src/libs/ck-libs/armci/armci_impl.h
- src/scripts/charmc
- src/util/charmrun-src/charmrun.C
Please **rebase** as a merge strategy.
> Windows autobuild fixes

- doc/converse/manual.rst
- src/conv-core/isomalloc.C
- src/conv-core/memory-gnu-internal.C
- src/conv-core/memory-gnu.C
- src/conv-core/memory-isomalloc.C
- src/conv-core/memory-isomalloc.h
- src/conv-core/memory.C
- src/conv-core/threads.C
- src/libs/ck-libs/armci/armci_impl.h
- src/libs/ck-libs/tcharm/tcharm.C
- src/util/cmitls.C
(The current 32-bit netlrts-linux build failure relates to my prior Isomalloc refactoring PR, and in my testing it is fixed in this one.)
Please **rebase** as a merge strategy.
> Use dlmalloc as Isomalloc's mempool

- doc/ampi/manual.rst
*Original date: 2018-10-16 23:16:33*
*Original PR: https://charm.cs.illinois.edu/gerrit/4701*
---
Change-Id: Ic0bfda263ec60854696c948fb504d88569bd4e40
> Documentation: update AMPI section on using array maps

- .circleci/config.yml
- .github/workflows/cmake.yml
- doc/ampi/manual.rst
- doc/converse/manual.rst
- src/conv-core/isomalloc.C
- src/conv-core/memory-isomalloc.C
- tests/ampi/jacobi3d/Makefile
- tests/ampi/mpich-test/generate_ampi_testlist
- tests/ampi/mpich-test/runtests.in
> Enable isomalloc_sync by default

- CHANGES
- CMakeLists.txt
- src/scripts/configure.ac
This merely duplicates the change just merged into master but now for the `charm-6.10.1` branch.
> Update release notes and version for 6.10.1 (#2737)

- src/scripts/conv-config.sh
- tests/ampi/privatization/test-f90-tlsglobals.f90
(Please rebase as a merge strategy.)
> Small privatization test fixes

- src/scripts/configure.ac
https://pubs.cray.com/content/S-2179/8.5/cray-c-and-c++-reference-manual-85/the-cray-compiling-environment
> add C++11 option for Cray compiler

- src/scripts/charmc
Should help with issues such as the one seen here: https://github.com/spack/spack/pull/15666 @s-sajid-ali
> charmc: make sure to link against pthread when using CkLoop

- build
> omp: make sure to enable task queue for multicore

- .travis.yml
Works around https://github.com/msys2/MSYS2-packages/issues/1962.
> Fix Windows CI failure

- buildcmake
> cmake: add extra verbose mode

- .github/workflows/changa.yml
> CI: add changa test

- .gitattributes
- cmake/Makefile.tests
> cmake: Fix Makefile.tests

- buildcmake
Same as in the old build system.
> cmake: add --only-configure option

- buildcmake
> cmake: restore --help option

- benchmarks/Makefile
- examples/Makefile
- tests/Makefile
Followup to #2467
Followup to #2489 
Reverts #2490 
Followup to #2581
> Reactivate Converse tests with CUDA builds

- CHANGES
- CMakeLists.txt
- src/scripts/configure.ac
> Update release notes and version for 6.10.2

- benchmarks/converse/commbench/ctxt.c
> Fix crashes in commbench/ctxt affecting clang and UCX autobuilds

- src/scripts/charmc
> charmc: pass through tbd files

- buildcmake
Fixes https://github.com/spack/spack/issues/18460.
> cmake: re-add --destination argument

- src/ck-core/CMakeLists.txt
- src/ck-ldb/LBManager.C
- src/ck-ldb/LBManager.h
- src/ck-ldb/TreeLB.C
- src/scripts/Make.depends
- src/scripts/Makefile
- src/util/json.hpp
- src/util/json_fwd.hpp
> LB: Forward declare JSON library to fix Kokkos compilation

- src/ck-ldb/TreeBuilder.h
> LB: Fix clang builds by removing templated JSON property accessors

- src/arch/cuda/hybridAPI/hapi_impl.cpp
Fixes #3056, which was caused by a `hapiWorkRequest` not being mapped to the proper CUDA stream.
This PR assigns the CUDA per-thread default stream to each `hapiWorkRequest` when it gets created.
I'm planning a separate PR that updates ChaNGa to not use the deprecated `hapiWorkRequest` API, so that it's easier to maintain compatibility of ChaNGa and Charm++.
> Use CUDA per-thread default stream in hapiWorkRequest

- doc/faq/manual.rst
Fixes broken link to section, for #3088.
> Update GPU section in FAQ

- CITATION.cff
- buildold
- doc/ampi/manual.rst
- doc/faq/manual.rst
- doc/index.rst
- doc/projections/manual.rst
- change http to https
- other URL fixes
Needs #3088
> doc: cleanup URLs in manual

- CHANGES
Please review and add things I may have missed or undersold.
> Add 6.11.0 release notes

- CMakeLists.txt
- cmake/converse.cmake
- cmake/hwloc.cmake
- src/scripts/Makefile
- src/scripts/charmc
- src/scripts/configure.ac
> Embed hwloc into libconverse

- .github/workflows/spack.yml
- cmake/detect-features-c.cmake
- cmake/detect-features-cxx.cmake
- src/scripts/charmc
- src/scripts/configure.ac
> Build the runtime with -ftls-model=initial-exec where available

- .github/workflows/buildold.yml
- .github/workflows/changa.yml
- .github/workflows/charm4py.yml
- .github/workflows/cuda.yml
- .github/workflows/multicore_darwin.yml
- .github/workflows/namd.yml
- .github/workflows/shellcheck.yml
- .github/workflows/spack.yml
- .github/workflows/ucx.yml
- .github/workflows/verbs.yml
> CI: enable checks from forks and fix Spack CI

- buildcmake
> cmake: fix lockless build

- src/libs/ck-libs/ampi/ampi.C
- src/libs/ck-libs/ampi/ampiimpl.h
Co-authored-by: Sam White <white67@illinois.edu>
> AMPI: Avoid pooling messages tagged as broadcast

- src/ck-core/ckarray.h
- Throw warning when migrations are attempted when the flag is set to false.
> Anytime migrations

- src/conv-core/convcore.C
See #2814, #2531, #2969, #3368
> Only call _IO_file_overflow on rank 0

- src/ck-core/ckarray.C
- src/ck-core/ckarray.h
This was automated reformating with clang-format
> Reformat ckarray.{C,h}

- CMakeLists.txt
- doc/charm++/manual.rst
- doc/conf.py
and other various fixes
Fixes #3089.
> doc: say that CMake is the default build system

- src/ck-core/cklocation.C
- src/xlat-i/xi-Entry.C
*Original date: 2017-06-02 22:51:18*
*Original PR: https://charm.cs.illinois.edu/gerrit/2581*
---
Change-Id: I03b10b8d92807fe031cfd2a81850777fc64cacc5
> Trace inline entry method calls in Projections

- cmake/hwloc.cmake
- src/scripts/Makefile
- src/scripts/configure.ac
> hwloc: Specify full set of compiler options to configure script

- src/arch/util/machine-common-core.C
> Avoid hang on exit with user-driven interop

- src/util/pup_stl.h
> PUP: Fix support for STL containers with custom comparators

- .circleci/config.yml
Improves build time by a bit over 2x (~30 minutes to ~10 and a bit minutes) through caching.
> CI: Update CircleCI

- .github/workflows/spack.yml
> Workaround for Spack CI failure on MacOS

- .github/workflows/spack.yml
> Revert "Workaround for Spack CI failure on MacOS"

- src/arch/mpi/machine.C
> MPI layer: print MPI library version as well as standard version

- src/ck-core/ckarrayindex.h
- src/ck-core/cklocation.h
- src/ck-core/objid.h
Please merge via rebase.
- objid: Fix overflow of home bits
- objid: Add extra assertions and improve messages
> Fix overflow of ID home bits and improve asserts

- src/ck-core/ckarray.C
- CkArray: Allow broadcasts of ckDestroy
- CkArray: Reorder ckDestroy to avoid extraneous move
> Reorder ckDestroy Related Calls

- src/util/charmrun-src/charmrun.C
Get CmiMyNode from PMIX_RANK environment variable.
Ensure node count in environment (if available) matches node count expected by charmrun.
Ensure CmiMyNode is less than node count.
Fix calling exit in a subshell as it only exits the subshell.
> Charmrun: Support ++mpiexec with PMIX, fix/add error checks

- build
- buildcmake
- buildold
- src/arch/gni/charmrun
- src/arch/mpi-win-x86_64/charmrun
- src/arch/mpi/charmrun
- src/arch/multicore/charmrun
- src/arch/ofi/charmrun
- src/arch/pami-linux-ppc64le/charmrun
- src/arch/pamilrts-linux-ppc64le/charmrun
- src/arch/ucx/charmrun
- src/arch/win/gatherflat.local
- src/arch/win/gathertree.local
- src/arch/win/system_ln
- src/libs/ck-libs/ampi/ampiCC
- src/libs/ck-libs/ampi/ampirun
- src/scripts/charmc
- src/scripts/gatherflat
- src/scripts/gathertree
- src/scripts/testrun
This should improve build performance by eliminating many process launches from each invocation of these scripts.
> Bashify conditionals in charmc, ampicc, charmrun, buildold

- src/ck-core/cklocation.C
- tests/charm++/Makefile
- tests/charm++/amr_1d_random/Makefile
- tests/charm++/amr_1d_random/amr_1d_random.C
- tests/charm++/amr_1d_random/amr_1d_random.ci
- tests/charm++/amr_1d_random/amr_1d_random.h
- tests/charm++/amr_1d_simple/Makefile
- tests/charm++/amr_1d_simple/amr_1d_simple.C
- tests/charm++/amr_1d_simple/amr_1d_simple.ci
- tests/charm++/amr_1d_simple/amr_1d_simple.h
- tests/charm++/anytime_migration/Makefile
- tests/charm++/anytime_migration/migrate.C
- tests/charm++/anytime_migration/migrate.ci
- tests/charm++/dynamic_insertion/Makefile
- tests/charm++/dynamic_insertion/dynamic_insertion.C
- tests/charm++/dynamic_insertion/dynamic_insertion.ci
- tests/charm++/dynamic_insertion/dynamic_insertion.h
- tests/charm++/dynamic_insertion_deletion/Makefile
- tests/charm++/dynamic_insertion_deletion/dynamic_insertion_deletion.C
- tests/charm++/dynamic_insertion_deletion/dynamic_insertion_deletion.ci
- tests/charm++/dynamic_insertion_deletion/dynamic_insertion_deletion.h
Adding tests from the spectre group #3662 
Resolves #3660 - The issue was caused by the location manager entry not being deleted correctly on dynamic deletions
> Fix stale location manager entry on dynamic deletions

- src/arch/mpi-darwin-arm8/conv-mach.h
- src/arch/multicore-darwin-arm8/conv-mach.h
- src/arch/netlrts-darwin-arm8/conv-mach.h
- src/arch/ofi/machine.C
- src/arch/pami/machine.C
- src/arch/pamilrts/machine.C
- src/arch/win/unix2nt_cc
- src/conv-core/conv-config.h
- src/conv-core/converse.h
- src/libs/ck-libs/ampi/ampif.C
- src/libs/ck-libs/ampi/romio/mpi-io/fortran/get_viewf.c
a batch of small fixes/improvements
> evan-fixes-2023-06

- src/scripts/charmc
This is a proposed fix for https://github.com/UIUC-PPL/charm/issues/3785
> charmc: do not use pipes. They hide exit codes

- src/arch/pamilrts/machine.C
Remove stray  endif, revise comments to match.
Closes issue #3828
> bugfix: remove stray endif, revise comments to match

- doc/charm++/manual.rst
Adding links to zero copy documentation, per request.
> Adding links to zero copy docs

- .github/workflows/ci.yaml
- CMakeLists.txt
- README.ampi
- buildcmake
- buildold
- doc/ampi/01-introduction.rst
- src/arch/multicore/charmrun
- src/libs/ck-libs/ampi/CMakeLists.txt
Multi PR to address the recent ci failures
#3864
#3870
#3863
> ci fixes bundle

- benchmarks/converse/selfsend/Makefile
- benchmarks/converse/selfsend/self_send.cpp
Times how long it takes for a PE to send some number of messages of a certain size to itself
> Add "send to self" converse benchmark

- .github/workflows/ci.yaml
We need this to fix the spack test again, they recently moved the charmpp package (and all other packages) into a new repo
> fix spack path again
