charmplusplus/charm

tests/ampi/privatization/Makefile
Several autobuild targets have been failing in these tests because older
platforms and toolchain versions are not as forgiving about loading a
binary as a shared object without explicitly building it as one. A
partial solution is possible by overhauling our build scripts to make
this happen, but it requires intensive and potentially fragile changes
to the build process of user applications, and at present the methods
would break entirely if Fortran module variables are present, with no
known workaround.
=> AMPI: Remove fsglobals and pipglobals from automated testing

.gitreview
This configuration file was used for Gerrit, which is not longer being used in favor of Github.
=> Bug #2241: Delete .gitreview

src/ck-core/ck.C
In charm4py, Chares have a method called migrate(toPe) which
previously lead directly to ArrayElement::migrateMe() in Charm++,
and with this patch now leads to ArrayElement::ckMigrate().
Although I haven't documented Chare.migrate() in the manual yet
(because I'm not sure it's useful for users), if I do document it
I'll just recommend to call it as an entry method, for example:
self.thisProxy[self.thisIndex].migrate(toPe), which I think also
makes the semantics clearer, because the user sees that it is
going to be scheduled and therefore not happen immediately.
If necessary, I can throw an error if it's not called as an entry
method, or make it so that it schedules an entry method
internally, but I'll leave that for later.
=> charm4py: fix CkMigrateExt by calling ckMigrate

src/libs/ck-libs/ampi/ampi.h, src/libs/ck-libs/ampi/ampi_noimpl.C, src/libs/ck-libs/ampi/ampiimpl.h
This resolves the issue with PMPI, the function pointer shim, and clang.
#2233
=> AMPI #2233: Improve robustness of PMPI weak symbol definitions

src/arch/mpi/charmrun, src/arch/ofi/charmrun
Solves an abort in `tests/charm++/partitions` when running with `++local`
=> Ignore ++local in MPI and OFI charmrun instead of running as standalone

tests/charm++/zerocopy/zc_post_modify_size/zc_post_modify_size.C, tests/charm++/zerocopy/zc_post_modify_size/zc_post_modify_size.ci
Previously, the group was named 'grp1', which was a global namespace
macro on Windows. The group is renamed from 'grp1' to 'grp'. For
consistency, the chare array was renamed from 'arr1' to 'arr' and
the nodegroup was renamed from 'nodegrp1' to 'nodegrp'.
=> ZC Post API Test: Rename identifiers for successful compilation on Windows

src/ck-core/ck.C
This fixes the multicore autobuild failures.
=> ZC Bcast Post API: Fix multicore bug when bcast root is not rank 0

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ampi.ci, src/libs/ck-libs/ampi/ampiimpl.h
*Original date: 2019-05-03 17:24:05*
*Original PR: https://charm.cs.illinois.edu/gerrit/2541*
---
Instead of sending the message payload eagerly and then getting an ack
when the recv'er actually matches it, now we use a rendezvous protocol,
only sending the payload after it has been matched.
The initial sync message (to ampi::genericSync) has no payload and its
refnum is the index of the sender's request. When the sync message is
matched by the recv'er, we delete that placeholder msg and send a
message back to the sender (to ampi::ssendAck) to get the payload back
in a normal AmpiMsg (via ampi::generic or ampi::genericRdma).
Change-Id: I6a8db194f63321a2247f707042d624d39fa3bef8
=> AMPI: implement (I)Ssend's using a synchronous rendezvous protocol

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ampiimpl.h
*Original date: 2019-05-03 17:26:06*
*Original PR: https://charm.cs.illinois.edu/gerrit/2557*
---
PE-local sends are done inline if the message is in-order and expected.
If not in-order and expected, then block the sender on the matching recv.
Build AMPI with -DAMPI_LOCAL_IMPL=0 to disable all local/inline sends.
Build AMPI with -DAMPI_LOCAL_THRESHOLD_DEFAULT=N and/or set the
environment variable AMPI_LOCAL_THRESHOLD=N, where N is the number
of bytes below which AMPI will not block the sender.
Change-Id: I244e400fa8e8750c2a999109572ca12124f4d672
=> AMPI: use Ssend protocol for PE-local sends to avoid intermediate copy

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ampi.ci, src/libs/ck-libs/ampi/ampiOneSided.C, src/libs/ck-libs/ampi/ampiimpl.h
*Original date: 2019-05-03 17:26:17*
*Original PR: https://charm.cs.illinois.edu/gerrit/2562*
---
In the payload of the Ssend message we serialize an SsendInfo object
that contains the sender's information, which can be used by the recv'er
if in the same logical node (process) to directly copy the real message
payload directly from the src buffer.
Also change the existing AMPI_LOCAL_THRESHOLD to AMPI_PE_LOCAL_THRESHOLD
to distinguish it from the new AMPI_NODE_LOCAL_THRESHOLD variable.
This means that all pt2pt messages with size greater than or equal to
the AMPI_NODE_LOCAL_THRESHOLD are now 'zero-copy' if in the same node.
Change-Id: Iebe9972b630fe17f4cc5c2a7ae0aa9f4b54b295b
=> AMPI: use Ssend protocol for Node-local sends to avoid intermediate copy

src/ck-core/ck.C, src/ck-perf/trace-common.C, src/ck-perf/trace-common.h
In some systems PAPI is unable to read cache events in certain cache levels, thus the highest cache level which can be read must be used.
=>  PAPI: dynamically check for availability of highest cache level events to add

src/ck-core/init.C
t.parent represents the logical node, which is the parent of my node.
However, CmiSyncSendAndFree expects a PE for its first argument and for that
reason, the ROChildCompletionMsg should be sent to the first PE of the parent.
This fixes the crash seen in https://github.com/UIUC-PPL/charm/issues/2286. 
However, the hang seen in https://github.com/UIUC-PPL/charm/issues/2286 is still unfixed because of QD support missing/being incorrect for the ZC API.
=> ZC RO Bcast: Send message to CmiNodeFirst(t.parent) instead of t.parent

src/ck-core/ckrdma.C
This fixes the verbs-smp autobuild failures seen in zc_post_modify_size. (http://charm.cs.illinois.edu/autobuild/old.2019_05_31__01_01/verbs-linux-x86_64-smp.txt)
=> ZC Bcast Post API: Fix verbs-smp crash on intermediate nodes

src/arch/gni/machine.C, src/arch/ofi/machine-onesided.C, src/arch/verbs/machine-ibverbs.C, src/ck-core/ckrdma.C, src/ck-core/ckrdma.h
This commit also adds the code for de-registration of source
buffers for Bcast operations implemented using reverse operations
when the buffer information object's mode is CK_BUFFER_UNREG.
Change-Id: Icea8bb56425b4d1a014b47bb795f4e34e220e99a
=> ZC API: set isRegistered after registration/de-registration

src/libs/ck-libs/ampi/ampi.C
In this case, any AMPI application would abort anyway on startup, so better to fail at AMPI compilation already.
=> AMPI: Fail compilation when unable to get binary path

src/conv-core/threads.C
When the CthScheduled function is inlined in the C file it cannot
be accessed via external linkage.  Removing the pointless (outside
of a header in C++) inline solves the problem.
=> fix #2268: undefined CthScheduled

src/ck-core/ckcheckpoint.C, src/ck-core/ckrdma.C
This fixes the multicore-win-x86_64 and mpi-win-x86_64-smp autobuild
failures on 06/05/2019 by keeping the windows linker happy.
=> Fix extern declarations of numZerocopyROops

benchmarks/charm++/communication_overhead/overhead_test.C
Test has always incorrectly ordered the local call
to operationFinished in the timed allocation case
to be before the remote message send. Whereas it should
always be after, as it is in the untimed allocation case.
Bug revealed by Phil's introduction of size testing in 2017.
Falsely attributed to verbs, as this bug is invariant
with network layer.
=> bugfix (#1473) : fix ancient ordering bug in benchmark

src/arch/gni/machine-onesided.C
In some cases, the small message send doesn't return SUCCESS and in
such cases, the message is buffered and sent later. This commit removes
the error checking code which checks for SUCCESS immediately after a
REG_AND_GET message is sent from LrtsIssueRput in gni/machine-onesided.C.
Change-Id: I82c9e6fe9bd7dab94754c4262f6c7032f96123ff
=> ZC GNI PUT: Remove immediate error checking for smsg send

benchmarks/charm++/zerocopy/direct_api/prereg/pingpong/pingpong.C, benchmarks/charm++/zerocopy/direct_api/reg/pingpong/pingpong.C, benchmarks/charm++/zerocopy/direct_api/unreg/pingpong/pingpong.C, benchmarks/charm++/zerocopy/p2pPingpong/megaZCPingpong.C, src/ck-core/ckrdma.C
The failures were caused after merging https://github.com/UIUC-PPL/charm/commit/97572b27ca70235dd5013d9184ba85215f02f775. 
This PR includes two fixes:
1. Pingpong benchmarks, which use the same set of buffers need to use CK_BUFFER_NODEREG to avoid RTS de-registration
2. QD counters have to be updated for de-reg messages.
=> Autobuild fixes after merging dereg support for ZC Direct API

benchmarks/charm++/pingpong/pingpong.C
This commit changes the deregMode of the buffer info objects using
the Direct API in benchmarks/charm++/pingpong to CK_BUFFER_NODEREG.
This is required to ensure that the buffers are not de-registered
after the completion of the operation.
=> Fix de-registration bug in benchmarks/charm++/pingpong/

doc/charm++/manual.rst, src/arch/gni/conv-common.h, src/arch/gni/conv-mach-syncft.h, src/arch/mpi/conv-common.h, src/arch/mpi/conv-mach-syncft.h, src/arch/netlrts/conv-common.h, src/arch/ofi/conv-common.h, src/arch/pamilrts/conv-common.h, src/arch/ucx/conv-common.h, src/arch/util/machine-broadcast.C, src/arch/verbs/conv-common.h, src/arch/verbs/conv-mach-syncft.h, src/ck-core/charm.h, src/ck-core/ck.C, src/ck-core/ck.h, src/conv-core/convcore.C, src/conv-core/converse.h, src/conv-ldb/cldb.bluegene.C, src/conv-ldb/cldb.neighbor.C, src/conv-ldb/cldb.none.C, src/conv-ldb/cldb.prioritycentralized.C, src/conv-ldb/cldb.rand.C, src/conv-ldb/cldb.spray.C, src/conv-ldb/cldb.test.C, src/conv-ldb/cldb.workstealing.C, tests/charm++/Makefile, tests/charm++/within_node_bcast/Makefile, tests/charm++/within_node_bcast/within_node_bcast.C, tests/charm++/within_node_bcast/within_node_bcast.ci
*Original date: 2019-04-25 17:03:02*
*Original PR: https://charm.cs.illinois.edu/gerrit/5068*
---
This respects [nokeep] and therefore would allow a receiver on a node to
forward a message to all PEs on a node, without copying the message, and
automatically deallocating the message after all PEs have received it (similar
to [nokeep] array broadcasts within a PE). With more work this could be more
integrated into all broadcasts/multicasts to save copying costs for large
readonly broadcasts.
Change-Id: I04dd6867245cd6fd8cd59b6125f9e806e5c27d52
=> Add API for doing a local broadcast to PEs on a node

src/ck-core/register.C
Minor bug fixes and cleanup.
This is all code inside `#if CMK_CHARMPY` blocks.
=> Fix Charm4py registering extra entry methods, and some cleanup

src/libs/ck-libs/ampi/ampiMisc.C
- Fix MPI_Info_dup to copy keyval pairs to the new info object
- Call resize upfront to avoid potential intermediate reallocations
=> AMPI: fix MPI_Info_dup to actually copy over keyval pairs

src/arch/uth/machine.C, src/conv-core/converse.h, tests/charm++/load_balancing/meta_lb_test/period_selection.C
Within node broadcasts need to be defined for the UTH layer and the MetaLB test
must assume 0 migrations when running on UTH.
=> Fix breakages in UTH from recent changes

doc/charm++/manual.rst
*Original date: 2019-04-26 21:14:50*
*Original PR: https://charm.cs.illinois.edu/gerrit/5053*
---
This change adds documentation for both p2p and broadcast operations
using the ZC EM Post API.
Change-Id: Ic17133de58a3bf551c3dae17c997390e7f8d4c02
=> doc: Add documentation for ZC EM Post API

src/arch/util/machine-smp.C
Previously, CmiNodeBarrier and CmiNodeAllBarrier had a bug on
non-Windows platforms because the same state variables were shared
between the two different kinds of barriers. This fixes that and is
also more portable, so it can replace both the previous Windows and
pthreads implementations of barriers.
=> Fix and replace SMP barriers with C++11 version

src/ck-ldb/MetaBalancer.C, src/ck-ldb/MetaBalancer.h, tests/charm++/load_balancing/meta_lb_test/period_selection.C
If the intial periodic call to check for 0 object PEs triggered at a weird
time (ie during migration), it could incorrectly detect an empty PE and cause
a mismatched reduction contribution. This makes it so the periodic call is only
checked if we have not received any load contributions at the time it triggers.
=> Fix a race in MetaLB regarding 0 object PEs

src/ck-core/ck.C
This fixes the bug that causes the heap-buffer-overflow in
multicore-linux-x86_64/tests/charm++/megatest.
=> Fix invalid heap access in CkSendMsgNodeBranchInline

src/ck-core/charm.h, src/ck-core/ck.C, src/ck-core/ckcallback.C
This essentially exposes CkSendMsgBranchMulti to Charm4py, useful
for list sends, and sending the same msg to children in a spanning
tree.
=> Charm4py: support sending same msg copy to multiple PEs in a Group

src/arch/util/machine-smp.C
I think this should fix the problem, but I still haven't tested, I'll update this when I do.
=> Remove leftover references to old Windows barrier implementation

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ampi.h, src/libs/ck-libs/ampi/compat_ampi.c
AMPI renames the application’s `main` function to `AMPI_Main`.
The return value from `AMPI_Main` is ignored, i.e. the runtime always assumes a return code 0.
Workaround: change `return` to `exit()`.
We need to propagate the real return code throughout AMPI and TCharm.
~~Potential issue:
How to handle `AMPI_Main` without return? E.g. when defined as void main(...), or with implied return 0 at end.
This might then return a random value from the stack.~~
Edit: 
- `void main()` doesn't work with AMPI (even without this PR).
- implied return 0 does actually return 0, so seems to be fine.
=> Propagate main()'s return code in AMPI

tests/charm++/load_balancing/meta_lb_test/Makefile, tests/charm++/load_balancing/meta_lb_test/period_selection.C
MetaLB makes a vague assumption about load starting balanced and uses that in
its decision process. This probably shouldn't be the case, but for now the test
starting imbalanced can cause issues.
=> Fix MetaLB test so that it starts balanced

src/ck-core/charm++.h, src/ck-core/charm.h, src/ck-core/ck.C, src/ck-core/ckcallback.C, src/ck-core/ckcallback.h, src/ck-core/ckreduction.C, src/ck-core/register.C
This adds support for a new sections implementation in Charm4py,
which I have tested internally, but would like other users to try
it. It doesn't interfere with existing functionality.
This removes Charm++ sections-related code from ckcallback when
building with CMK_CHARMPY. The rest of the changes only affect
CMK_CHARMPY code.
=> Charm4py: support new sections implementation

src/libs/ck-libs/ampi/ampi.C
In particular, do not clear the all of the status fields, just the ones
required by the standard.
=> AMPI: Fix handling of MPI_PROC_NULL

src/libs/ck-libs/ampi/ddt.C
Fixes mpich's bottom.c test.
lb is initialized to zero, and xlb < lb was always false.
=> AMPI: fix LB/UB of DDT_Struct

src/ck-ldb/LBDBManager.C
This is a bug in LB, which had been incorrectly discussed in core in the past. This fix should make its way to the new LB framework as well.
=>  Fix incorrect AtSync barrier check

tests/ampi/megampi/Makefile, tests/ampi/megampi/test.C
After merging the changes to AMPI to use the zero copy direct API
for all MPI_(I)Ssend's and for all large messages, we saw aborts
in the bgtest target for tests/ampi/megampi/ from BgMyRank being
called by the RTS on the scheduler thread inside CmiIssueRput().
This commit disables the tests for MPI_Issend when testing BigSim.
=> BigSim: workaround AMPI zero copy API issue in MPI_Issend

src/libs/ck-libs/ampi/ddt.C
Reverts UIUC-PPL/charm#2384. LB/UB calculation is now broken in a different way.
=> Revert "AMPI: fix LB/UB of DDT_Struct"

src/conv-ldb/cldb.none.C, src/conv-ldb/cldb.test.C
Old extensions (i.e., CldEnqueueGroup) to cldb.rand were not propagated to cldb.none or cldb.test. This replicates that so these can be selected via -balance and function correctly to govern singleton chare placement. Neither of these strategies is good as a balancer, but none provides a deterministic approach that assists various debugging scenarios.  cldb.test provided simply for completeness.
=> bugfix : CldEnqueueGroup for cldbs none and test

tests/charm++/zerocopy/bcast_nonzero_root/bcast_nonzero_root.C, tests/charm++/zerocopy/bcast_nonzero_root/bcast_nonzero_root.ci
Previously, the group was named 'grp1', which was a global namespace
macro on Windows. The group is renamed from 'grp1' to 'grp'. For
consistency, the chare array was renamed from 'arr1' to 'arr' and
the nodegroup was renamed from 'nodegrp1' to 'nodegrp'.
=>  ZC non-zero bcast test: Rename identifiers for Windows builds

src/ck-core/envelope.h, src/ck-core/init.C, tests/charm++/Makefile
envelopeEventID is the ckpv that monotonically increases
with each envelope (and therefore message).  However, in SMP
the envelope allocated and enqueued in the initDone process
is invisible to the record/replay process and can occur
on any PE in the node.  That creates a non-deterministic
race condition in the PE:envelopeEventID tuple space.
This workaround simply avoids incrementing the envelopeEventID
on the PE that triggers doneInit. This allows otherwise
deterministic SMP applications to record/replay with proper
fidelity.
=> bugfix #1999: record/replay may hang in SMP

src/ck-core/ckrdma.C
The bug was introduced by the patch that supported Bcast from
a non-zero root. That patch required 'rootNode' to be pupped/unpupped
after 'numops' in a ZC metadata message. CkRdmaPrepareP2PMsg
opens up the ZC metadata message to modify it for supporting
de-registration in P2P CMA transfers and requires the additional
'rootNode' to be pupped/unpupped for correct processing of the
metadata message.
=> ZC p2p CMA: Unpup/Pup rootNode in CkRdmaPrepareP2PMsg

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ampiOneSided.C, src/libs/ck-libs/ampi/ampiimpl.h, src/libs/ck-libs/ampi/ddt.C, src/libs/ck-libs/ampi/ddt.h
Now attributes are stored independently for each Comm/Type/Win instead
of per-rank.
Co-authored-by: Sam White <white67@illinois.edu>
=> AMPI: Revamp keyval and attribute handling

src/arch/util/machine.h
The MACHINE_DEBUG macro has been silently broken for quite
a while.  Fix is to replace "str" with "#str" so it gets
stringified in the nested MACHSTATE prints.
=> bugfix: use # to stringify MACHSTATE format strings

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ampiimpl.h
AMPI previously kept around the original CkNcpyBuffer objects
used in all zero copy operations. Instead, one should get a
CkNcpyBuffer object back from zero copy completion callbacks
via the CkDataMsg::data field.
=> AMPI: fix bug in zero copy buffer deregistration

src/arch/mpi-win64/conv-mach.h
This fixes the mpi-win-smp ZC QD test, which was hanging because
the QD counter from the comm thread was not being accounted for in the
QD detection process.
I tested autobuild style 'make test' with this patch and all tests seem to be running fine.
=> Enable CMK_IMMEDIATE_MSG on mpi-win64 platforms

tests/charm++/sdag/refnum.ci
=> Fix CkDataMsg access in sdag tests for PAMI

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ampiimpl.h
*Original date: 2019-05-03 19:18:19*
*Original PR: https://charm.cs.illinois.edu/gerrit/4143*
---
Change-Id: I520a6d8598a0ec6e0dc553ebaeb7b1a481d52c95
=> AMPI cleanup: move MPI_Waitall implementation into ampiParent::waitall()

src/libs/ck-libs/io/fs_parameters.c
=> CkIO: Use default stripe size when automatic detection errors

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ampiMisc.C, src/libs/ck-libs/ampi/ampiOneSided.C, src/libs/ck-libs/ampi/ampi_mpix.C, src/libs/ck-libs/ampi/ampi_noimpl.C, src/libs/ck-libs/ampi/ampiimpl.h
When enabled, prints each MPI function call of an application with the PE/VP that made the call, as well as the names and values of the call arguments.
This is disabled by default, and needs to be enabled by setting `AMPI_DO_DEBUG` to 1. This will also enable `AMPI_DEBUG`.
Printing is done using `std::cout`, and not `CmiPrintf` or `ckout` since:
- `CmiPrintf` etc. can't do automatic formatting of arguments based on their types.
- `ckout` can't print (e.g.) function pointers.
Example output:
```
[3:3] AMPI_Barrier(comm=9000000)
[0:0] AMPI_Scatter(sendbuf=0x7fb5b91066c0, sendcount=1, sendtype=1, recvbuf=0x580103a64, recvcount=1, recvtype=1, root=3, comm=9000000)
[0:0] AMPI_Reduce(inbuf=0x58010393c, outbuf=0x580103930, count=1, type=1, op=2, root=3, comm=9000000)
[2:2] …
```
=> AMPI: debug API arguments

src/libs/ck-libs/ampi/ddt.C, src/libs/ck-libs/ampi/ddt.h
Solves a performance bug where CkDDT::insertType was linear in
the number of total types.
=> CkDDT: Replace vector type with set freeTypes

src/ck-core/charm.h, src/ck-core/ck.C, src/conv-core/convcore.C, src/conv-core/converse.h
I was able to get the different interface layers in Charm4py to work directly with CmiPrintf and CmiAbort
=> Revert charm4py cmiwrappers

src/ck-core/ckreduction.h
Can we merge this and #2485 before the release? I'm not sure when 6.10 release is going to happen, and this is stopping me from merging some things on charm4py master. These won't break Charm++ and the changes are in #CMK_CHARMPY blocks
=> Expose logical bool reducers to Charm4py

doc/charm++/manual.rst, src/arch/ucx-linux-arm8/conv-mach-ompipmix.h, src/arch/ucx-linux-arm8/conv-mach-ompipmix.sh, src/arch/ucx-linux-arm8/conv-mach-slurmpmi.h, src/arch/ucx-linux-arm8/conv-mach-slurmpmi.sh, src/arch/ucx-linux-arm8/conv-mach-slurmpmi2.h, src/arch/ucx-linux-arm8/conv-mach-slurmpmi2.sh, src/arch/ucx-linux-arm8/conv-mach-smp.h, src/arch/ucx-linux-arm8/conv-mach-smp.sh, src/arch/ucx-linux-arm8/conv-mach.h, src/arch/ucx-linux-arm8/conv-mach.sh
Adding the file to src/arch/ucx-linux-arm8 that allow "ucx-linux-arm8" to build.
=> Armv8 does not build with UCX

src/util/charmrun-src/charmrun.C
This retains the clean output of ASan when running Charmrun with
++local.
=> Eliminate calls to strndup from charmrun.C

src/conv-core/CMakeLists.txt, src/conv-core/cmidemangle.h, src/conv-core/convcore.C, src/scripts/Make.depends
Adds a new API function, `std::string CmiDemangle(const char *name)`, to demangle C++ symbol names platform-independently. Use this function to print demangled stack traces, e.g. on `CmiAbort()`.
Based on boost 1.71.0.
old:
```
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: Usage: ./simpleBcast <array-size>
[0] Stack Traceback:
[0:0] 0   simpleBcast   0x000000010aec75c1 CmiAbort + 177
[0:1] 1   simpleBcast   0x000000010ad72418 _ZN4MainC1EP8CkArgMsg + 104
[0:2] 2   simpleBcast   0x000000010ad7235a _ZN12CkIndex_Main19_call_Main_CkArgMsgEPvS0_ + 74
[0:3] 3   simpleBcast   0x000000010adb843f _Z10_initCharmiPPc + 4751
[0:4] 4   simpleBcast   0x000000010aec8e3f ConverseInit + 1247
[0:5] 5   simpleBcast   0x000000010adb93ee charm_main + 46
[0:6] 6   simpleBcast …
```
=> add C++ demangling API and use it for backtraces

.github/workflows/verbs.yml
Verbs is buildonly, as the machine layer needs an actual device to run.
=> Add buildonly verbs test

CMakeLists.txt
=> cmake: fix replaysystem spelling

src/ck-ldb/lbdb.h
If d.data is NULL, the 'data' pointer of the new instance remains
unintialized, which can cause segfaults if the instance is deleted
afterwards.
=> Fixed uninitialized pointer in LBObjUserData copy constructor

src/ck-core/cklocation.C, src/ck-core/cklocation.h
This replaces the buggy busy-wait that reschedules the messages
until the managers are created (which doesn't work because
immigrate messages are expedited).
=> CkLocMgr: buffer immigrate messages if array managers don't exist

examples/ampi/Cjacobi3D/jacobi.C, src/conv-core/cputopology.C, src/conv-core/threads.C, src/util/charmrun-src/charmrun.C, src/util/sockRoutines.h, tests/ampi/jacobi3d/jacobi.C
Followup from the removals of AIX support (39643aa) and Myrinet (102a60c).
=> cleanup: remove vestiges of CMK_AIX / CMK_USE_GM / CMK_USE_MX

.travis.yml
Currently, `brew install ccache` errors, failing the build.
=> remove ccache from travis ci Mac build

src/scripts/charmc
This should be cherry-picked for 6.10.
=> Bug #2495: remove -isysroot from charmc arguments

src/arch/cuda/hybridAPI/hapi_impl.cpp, src/ck-core/ck.C, src/ck-core/init.C
Resolves #2467 by removing dependencies on the Charm++ layer: `CkVec`, `CkCallback`, `QdCreate`, and `QdProcess`.
=> HAPI: Remove dependency on Charm++ layer and fix WorkRequest instrumentation

src/ck-core/register.C
Should fix CkLoop registration. Please test.
=> Bug #2591: Only set __registerDone on rank 0

.github/workflows/verbs.yml
Fixes the CI errors seen today.
=> GitHub CI: run apt-get update to avoid installing old packages

src/ck-core/ckrdma.C, src/ck-core/ckrdma.h, src/util/cmirdmautils.C, src/util/cmirdmautils.h
Previously, on intermediate nodes, when rgets on the child nodes were being
executed as reverse operations (PUT from source instead of a GET from destination),
the source buffer was de-registered twice on the intermediate nodes, causing a failure.
This de-registration (for UNREG modes) is only applicable to root nodes.
With this commit, the root node for a ZC Bcast is stored in NcpyOperationInfo
and de-registration is performed only when the reverse operation involves
the root node as the source. (and not when an intermediate node is the source)
=> ZC Bcast API: Fix de-registration bug on parent nodes after reverse op

src/scripts/configure.ac
Avoids the automake warning discussed in #2599.
=> Bug #2599: workaround for building shared hwloc library

src/libs/ck-libs/ampi/ampiCC, src/scripts/charmc
Helps with (e.g.) configure scripts that parse the output of `-v`, `--version`, `-print-search-dirs` to detect compiler configurations.
=> charmc/ampicc: pass through certain compiler options even without file to compile

contrib/hwloc/config/hwloc.m4, contrib/hwloc/configure.ac
Workaround for #2606. The check is stricter than what
hwloc actually requires, and hwloc compiles fine without it.
=> hwloc: disable C99 check

src/arch/ucx/machine.C
Reverting should fix:
https://github.com/UIUC-PPL/charm/issues/2597
https://github.com/UIUC-PPL/charm/issues/2616
Reverting this will cause one of the ChaNGa test cases to fail (reported by @trquinn), so we'd still have to find a fix for that crash generated by the recursion shown. However, the generic case of running charm programs will still work, which is more important.  
```
Core was generated by `./ChaNGa.ucx +ppn 55 +setcpuaffinity +commap 0 +pemap 1-55 h148.cosmo50PLK.6144'.
Program terminated with signal 11, Segmentation fault.
#0  0x00002af5abfe0ab9 in sysmalloc () from /lib64/libc.so.6
warning: File "/opt/apps/gcc/8.3.0/lib64/libstdc++.so.6.0.25-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
To …
```
=> Revert new ucx changes which are introducing crashes

src/util/charmrun-src/charmrun.C
Prevents error 
`
charmrun.C(4528): error C2664: 'BOOL CreateProcessA(LPCSTR,LPSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCSTR,LPSTARTUPINFOA,LPPROCESS_INFORMATION)': cannot convert argument 2 from 'const char *' to 'LPSTR'
`
=> charmrun: const_cast CreateProcess argument

src/arch/ucx/machine.C
Need to initialize `maxval` by `0` to avoid it having a garbage when
`runtime_get_max_vallen()` returns (we cast it to `int` as runtime API requires)
Fixes one of the problems reported in #2597
=> UCX: Fix eps initialization

src/arch/ucx/machine.C
@brminich, do you see anything wrong with this patch? I believe each request will end up with the same idx as it would have without the patch, but the order in which `handleOneRecvedMsg` is called and `ucxCtx.rxReqs[idx]` is assigned is now FIFO instead of LIFO. Hopefully that won't break anything.
=> UCX: Replace recursion with iteration in UcxPostRxReq

src/arch/common/cc-gcc.sh, src/arch/common/conv-mach-darwin.sh, src/arch/mpi-darwin-x86_64/conv-mach.sh
This fixes building mpi-darwin-x86_64, which fails due to not seeing -stdlib=libc++.
=> Cleanup: Make mpi-darwin-x86_64/conv-mach.sh use common/conv-mach-darwin.sh

src/ck-ldb/CentralLB.C, src/ck-ldb/DistBaseLB.C
Another fix related to PR #2630. If there are bugs in strategies which create migration requests those are not currently caught. This was the case in Distributed LB, an external collaborator caught the weird behavior.
Change-Id: I75cd3c67bbe3f9d7e705d1f4ca96f9c8451f4b93
=> Prevent self migrations in LB strategies

src/ck-ldb/DistributedLB.C
This bug was discovered when looking at PR #2630.
=> Ensure that the distributed LB transfer threshold never applies to underloaded PEs

src/ck-core/ckcheckpoint.C
Here is my proposed fix to issue #2627.  The nodegroup file goes into a different directory than the group or array files, so make sure that directory is created if needed.
=> ckCheckpoint: create subdirectories for nodegroup files, if needed.

src/ck-core/ckcheckpoint.C
ostreamstring::rdbuf() does not do the obvious thing.  Use str() instead.
=> Checkpoint: use str() instead of rdbuf() to copy dirPath.

src/libs/ck-libs/ampi/ampif.h
The MPI standard specifies the constants MPI_TAG, MPI_SOURCE, and MPI_ERROR
as indices into an MPI_Status object. It allows the definition of more fields inside
the status object, but those fields (such as MPI_COMM for us) should be private
to avoid namespace collisions.
=> AMPI #2655: hide MPI_COMM constant from public Fortran header

doc/charm++/manual.rst, src/conv-core/cpuaffinity.C
Closes #2657.
The user can pass options like `+pemap L0-7` to use logical PU indices instead of indices assigned by the OS.
Also updates program output and error messages to make it clear which version (OS indices vs. logical indices) is being used.
Tested on LLNL Lassen.
=> Support logical PU indices in +pemap and +commap

src/arch/mpi-win64/charmrun
Fixes #2674.
Followup from #2394.
Could be cherry-picked to 6.10.
=> charmrun: fix syntax error in mpi win

src/scripts/configure.ac
CMakeLists.txt already disables these options.
Please verify that this resolves the issue.
Closes #2679
=> hwloc #2679: Disable GL and Cairo at configure time

src/arch/mpi-darwin-x86_64/conv-mach-smp.h, src/arch/mpi-darwin-x86_64/conv-mach.h, src/arch/multicore-darwin-x86_64/conv-mach.h, src/arch/netlrts-darwin-x86_64/conv-mach-smp.h, src/arch/netlrts-darwin-x86_64/conv-mach.h
This replaces uJcontext as the default threading implementation. Its use of setjmp/longjmp causes failures on Darwin during checkpoint restart.
=> Darwin: Use uFcontext threads by default

.github/workflows/bigsim.yml, .github/workflows/cmake.yml, .github/workflows/uth.yml, .github/workflows/verbs.yml
Should prevent long-running CI hangs (default timeout is 360 mins) such as the one seen in #2458.
=> GitHub CI: limit jobs to 45 minutes

src/conv-core/memory-gnu-internal.C, src/conv-core/memory-gnu.C
I've verified correctness by running my malloc stress test (benchmarks/ampi/isomalloc) built with `-memory gnu`.
To make this PR easier to review, the following diff compares memory-gnu-internal.C with upstream dlmalloc-2.8.6's malloc.c. It consists of comments, silencing unused variable warnings, and a C++ build fix. Except for the topmost comment these changes are already in Charm.
```diff
diff --git a/malloc.c b/malloc.c
index 649cfbc..6077676 100644
--- a/malloc.c
+++ b/malloc.c
@@ -1,2 +1,20 @@
/*
+  This version of ptmalloc3 has been updated to use the latest dlmalloc
+  version, 2.8.6. It appears that all malloc.c changes in ptmalloc3 were
+  merged into dlmalloc as of version 2.8.4. Differences between dlmalloc
+  and this file are extremely minimal, so all comments apply despite …
```
=> Memory: Update dlmalloc in ptmalloc3 to version 2.8.6

src/conv-core/memory-charmdebug.C, src/conv-core/memory-gnu.C, src/conv-core/memory-isomalloc.C, src/conv-core/memory-leak.C, src/conv-core/memory-lock.C, src/conv-core/memory-os-wrapper.C, src/conv-core/memory-paranoid.C, src/conv-core/memory-verbose.C, src/conv-core/memory.C
- Use of the ptmalloc3 "gnu" allocator has been made more modular so that it is now easier to add new malloc backends besides it and the OS allocator, as well as to allow further work toward using it as a memory pool for Isomalloc, HAPI, or more, if desired.
- Underlying malloc implementations are now exposed in two ways: `mm_*` symbols lock if the implementation requires it (such as ptmalloc3), while `mm_impl_*` symbols do no locking (unless the implementation, such as the OS, does its own). This allows our memory layers to handle locking as efficiently as possible.
- `-memory leak`, `-memory paranoid`, and `-memory verbose` are now thread-safe in all circumstances, including the default `-memory os-*`, by handling locking as part of their implementations. `-memory charmdebug` is also …
=>  Memory: Clean up locking around allocator implementations

.github/workflows/ucx.yml
Validation sometimes fails in the middle of testing due to the timeout.
=> Increase UCX CI build timeout to 60 minutes

examples/charm++/reductions/allReduce/AllReduce.C, examples/charm++/reductions/allReduce/AllReduce.ci, examples/charm++/reductions/allReduce/AllReduce.h
Fixes failure seen in http://charm.cs.illinois.edu/autobuild/old.2020_02_03__01_02/multicore-darwin-x86_64.txt
=> Fix causality issue in examples/charm++/reductions/allReduce

src/libs/ck-libs/multiphaseSharedArrays/msa-DistPageMgr.ci, src/libs/ck-libs/multiphaseSharedArrays/msa-DistPageMgr.h
Xlat-i adds `std::move` to function arguments while unmarshalling for zero-copy support. This did not preclude compilation of the MSA library, but anything trying to use its headers will fail to build. This patch allows MSA programs to build again.
=> allows msa programs to build with std::move, as added by xlat-i

src/conv-core/CMakeLists.txt, src/conv-core/memory-record.C, src/conv-core/memory.C, src/scripts/Makefile, src/scripts/charmc
Generates an MPI program that repeats the exact sequence of heap operations observed on each PE. Can be used for debugging and performance analysis of memory allocators as well as heap behavior of user codes.
=> Add Heap Record-Replay, -memory record

src/arch/verbs/machine-ibverbs.C
Verbs started rejecting setting retry_cnt to 20 because this is only
a 3-bit field, so the maximum legal value is 7.  This caused a
retry using "QLOGIC" values, which attempted to modify the mtu,
but the mtu flag was not set and mtu could not be modified at this
point of setup anyway, so the value was only changed for future
nodes attempting to connect and was in general inconsistent,
resulting in "Work completion error in sendCq" Charm++ aborts
along with mlx5 driver "got completion with error" messages.
Fix is to always set retry_cnt to 7 and don't try to change mtu.
=> Fix verbs on new InfiniBand hardware/drivers

src/arch/mpi/machine.C, src/arch/netlrts/machine.C, src/arch/verbs/machine.C
Partial revert of 8c85a3debc2254d68f8aa50c6ec0b1e302c86131, which
had set Cmi_truecrash=1 whenever CmiNumNodes()<=32.  This would
cause users to see a segfault when CmiAbort() was called due to
input errors, safety checks, etc., which they would interpret as
a bug in the application.  Now builds with CMK_OPTIMIZE=1 will
only segfault in CmiAbort() if ++debug or +truecrash are specified
by the user on the command line at run time.
=> Revert CmiAbort segfaults in production builds

src/arch/netlrts/machine.C, src/arch/ucx/conv-common.h, src/arch/util/machine-common-core.C, src/arch/verbs/machine.C, src/ck-core/debug-charm.C, src/conv-ccs/conv-ccs.C, src/conv-core/convcore.C, src/conv-core/debug-conv.C, src/conv-core/debug-conv.h
Adapted from #2711 for Charm 6.10 due to conflicts with #2540. In particular, 6.10 only sets cmiArgDebugFlag as part of the statement `if(CmiMyRank() == 0) CpvAccess(cmiArgDebugFlag) = 1;`.
=> [6.10.1] cmiArgDebugFlag and CMK_CCS_AVAILABLE fixes

src/libs/ck-libs/ampi/ampi.C
MPI_Waitsome and Testsome require users to be aware of the difference between NULL and
valid requests. AMPI used to return MPI_REQUEST_NULL for eagerly sent messages, in order
to avoid the overhead of request creation. Now we pool requests anyways, so just make the
real requests. Also fix an indexing error in Waitsome and Testsome.
=> AMPI: fix MPI_Waitsome by creating valid requests for eager msgs

src/scripts/Makefile
This fixes the ofi build failures seen during nightly build.
Change-Id: Icd33546865d866c3fb1f33861389bbb216d696e4
=> Add missing headers as makefile targets

src/conv-core/threads.C, src/util/cmitls.C, src/util/cmitls.h
This commit implements the bookkeeping necessary for macOS to use
thread-local storage buffers as allocated by Isomalloc instead of
allocating and maintaining its own non-migratable buffers.
=> Fix tlsglobals migration on macOS

src/ck-core/init.C
Additionally, this commit also modifies the warning message printed
since the previous message was confusing.
=> Do not print warning message for +CmiSleepOnIdle when arg is passed

src/util/cmitls.C
Should solve the following:
```
../bin/charmc  -optimize -production   -I.   -c -o cmitls.o cmitls.C
cmitls.C: In function â€˜void __tls_init()â€™:
cmitls.C:482:47: internal compiler error: Segmentation fault
thread_local CmiTLSPlaceholderWithConstructor CmiTLSPlaceholderStruct{};
^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
Preprocessed source stored into /tmp/cckhEghy.out file, please attach this to your bugreport.
Fatal Error by charmc in directory /scratch/autobuild/netlrts-linux-x86_64-syncft/charm/netlrts-linux-x86_64-syncft/tmp
Command g++ -DCMK_GFORTRAN -I../bin/../include -D__CHARMC__=1 -I. -O3 -fno-stack-protector -std=c++11 -c cmitls.C -o cmitls.o returned error code 1
charmc …
```
=> Remove thread_local with constructor from cmitls.C

build, buildcmake
This leaves 32 bits for the element id, 29 for the collection id, and 3 for the tag bits.
=> AMPI: increase objid collection bits for AMPI-only builds

src/arch/util/machine-smp.C, src/conv-core/converse.h
* Disable C11 stdatomic.h support with GCC < 7.1 when OpenMP or
Objective-C are in use
* Add MSVC intrinsics for memory fences
* Always create cmiMemoryLock: it won't be obvious to the runtime, which
compiles as C++, if C user code such as the Converse tests need it, e.g.
for CpvInitialize
=> Improve portability of CmiMemoryAtomic*/ReadFence/WriteFence

cdash/CTestTestfile.cmake, cdash/run_autobuild.sh
- Increase timeout for each test to 40 minutes.
- Split up building tests into tests/ examples/ benchmarks/ for better support with the cmake build system.
- Don't exit immediately on error in run_autobuild.sh (to make sure
the build directory is cleaned up).
- More robust detection of whether the script was started by cron or not.
=> CDash updates

src/arch/common/cc-gcc.sh, src/arch/common/cc-icc.sh, src/arch/common/cc-pgcc.sh, src/arch/common/conv-mach-craype.sh, src/arch/common/conv-mach-gfortran.sh, src/arch/common/conv-mach-ifort.sh, src/arch/common/conv-mach-pgf90.sh, src/arch/mpi-linux-ppc/cc-mpicxx.sh, src/arch/mpi-linux-x86_64/cc-mpicxx.sh, src/arch/multicore-arm7/conv-mach.sh, src/arch/multicore-arm8/conv-mach.sh, src/arch/multicore-linux-ppc/conv-mach.sh, src/arch/multicore-linux32/conv-mach.sh, src/arch/multicore-linux64/conv-mach.sh, src/arch/netlrts-linux-arm7/conv-mach.sh, src/arch/netlrts-linux-arm8/conv-mach.sh, src/arch/netlrts-linux-ppc/conv-mach.sh, src/arch/netlrts-linux-x86_64/conv-mach.sh, src/arch/netlrts-linux/conv-mach.sh, src/arch/ofi-linux-x86_64/conv-mach.sh, src/arch/pami-linux-ppc64le/conv-mach.sh, src/arch/ucx-linux-arm8/conv-mach.sh, src/arch/ucx-linux-x86_64/conv-mach.sh, src/arch/uth-linux-x86_64/conv-mach.sh, src/arch/uth-linux/conv-mach.sh, src/arch/verbs-linux-ppc64le/conv-mach.sh, src/arch/verbs-linux-x86_64/conv-mach.sh, src/scripts/conv-config.sh
Also tries to match gfortran version to gcc version if specified. For
example: `./build netlrts-linux-x86_64 gcc-8` will use gfortran-8.
=> Clean up gfortran build system details

build, buildcmake, src/arch/common/cc-clang.sh, src/arch/common/cc-gcc.sh, src/arch/common/cc-msvc.sh, src/arch/win/unix2nt_cc, src/libs/ck-libs/ampi/pathstub.sh, src/libs/conv-libs/openmp_llvm/runtime/src/kmp.h, src/scripts/configure.ac, src/util/charmrun-src/charmrun.C
- Charmrun: Fix buffer overflow in local process launch on Windows
- unix2nt_cc: Recognize additional variants of -g
- Windows: Fix /usr/bin/link workaround with VS 2017 and newer
- Windows: Don't try to build ROMIO by default
- Windows: Avoid -fPIC and -fPIE unknown argument warnings
- unix2nt_cc: Add support for creating DLLs
- AMPI: Add $ORIGIN safeguard to pathstub.sh
- configure: Fix -rdynamic test when using clang
- src/libs/conv-libs/openmp_llvm: Fix "error: template with C linkage"
(Please rebase as a merge strategy.)
=> Various cleanup relating to fsglobals work

src/ck-ldb/DistributedLB.C, src/ck-ldb/DistributedLB.h
With the new multiphase approach, as load thresholds change, it was possible
before that a PE which had accepted load became "overloaded" at a certain
threshold and would try to transfer load. This behavior could cause crashes
and/or hangs under the right circumstances and was never intended.
=> Ensure a PE that is initially underloaded never tries to transfer load.

src/ck-core/cklocation.C, src/ck-core/cklocation.ci
By overriding populateInitial but not procNum, BlockMap was broken
and resulted in an influx of updateLocation messages upon array
creation. Adding a procNum function to fix this would have made it
equivalent to DefaultArrayMap.
Change-Id: Id3a53d7dc47d98d106eeda728c3d714bf723373d
=> Fix broken BlockMap

cdash/CTestTestfile.cmake
On Windows systems, `./build` does not create the usual top-level `bin`, `tmp`, etc. symlinks, which ctest used to find the directory of tests to run. This patch changes this to determine the name of the directory where the `include/VERSION` file is located, and use that directory to locate the `tests/`, `examples/`, and `benchmarks/` directories. 
Note that this might fail when there are multiple builds within the same charm directory, as there will be multiple `include/VERSION` files. Since this is meant just for automated test builds, we can ignore this limitation for now.
=> cdash/ctest: Fix test directories on Windows

src/ck-core/cklocation.C
CkLocMgr deals only with element IDs. This fixes the pathway where
CMK_GLOBAL_LOCATION_UPDATE is enabled so that it does not pass IDs
with collection information to CkLocMgr functions
=> LocMgr: Fix IDs for CMK_GLOBAL_LOCATION_UPDATE

src/conv-core/memoryaffinity.C
Issue found when building with `verbs-linux-x86_64` version.
=> Cast return value of malloc() to correct pointer type

benchmarks/converse/randomttl/randomttl.C
This fixes the crash in the program caused because of accessing
variables before their initialization. Previously, the vector 'peVector'
was being accessed by a message handler function before the values in
'peVector' were set.
=> Converse randomttl benchmark: Move variable init to main function

benchmarks/converse/randomttl/randomttl.C
Fixes Windows autobuild failures.
=> Converse randomttl benchmark: #include <numeric>

CMakeLists.txt, cmake/README.md
no functional change, just removes quotes from command line passed to charmc.
=> cmake: clean up extra args parsing

src/util/boost-context/CMakeLists.txt
Fixes error introduced in #2846.
=> cmake: remove duplicate charmc for boost

CMakeLists.txt
The CheckLanguage module didn't find the same version of gfortran as gcc in some cases.
Fixes #2851 (at least on golub).
=> cmake #2851: cleaner fortran support

src/ck-core/charm.h, src/ck-core/debug-charm.C, src/ck-core/msgalloc.C, src/ck-core/sdag.h, src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/pythonCCS/charmdebug-python.C, src/xlat-i/sdag/CEntry.C, src/xlat-i/sdag/constructs/SdagEntry.C, src/xlat-i/xi-Parameter.C
A common paradigm in the codebase is to increment the refcount of a
message by using CmiReference(UsrToEnv(msg)), this creates a function
to simplify this usage.
=> Add CkReferenceMsg function

src/ck-ldb/TreeLB.C, src/ck-ldb/TreeLevel.h
=> Use CkReferenceMsg to avoid duplicating TreeLB messages

src/ck-core/cklocation.C, src/ck-core/ckmulticast.C
Charm++ can be compiled and run with -std=c++20 now.
=> cast fixes for C++20

src/libs/ck-libs/ampi/ampiCC
Exporting AMPI_BUILD_FLAGS with values such as `-charm-shared` will
allow passing options without modifying an MPI program's build scripts.
=> ampiCC: Accept arguments from environment variable

examples/charm++/cuda/hello/hello.C
The CUDA hello example only offloaded kernels from `n_chares-1` chares (which excludes the last chare). This patch fixes it so that all chares offload kernels to the GPU, including the last one.
=> Fix CUDA hello example to offload kernels from all chares

CMakeLists.txt, README.md, buildcmake, smart-build.pl, src/arch/common/conv-mach-pedantic.sh
-pedantic can just be passed to ./build if needed; -Wno-long-long is
irrelevant in C++11
=> build: remove pedantic option

src/libs/ck-libs/CMakeLists.txt
Fixes darwin autobuild failure.
=> cmake: add jpeg include dir

CMakeLists.txt, cmake/Makefile.tests
For compatibility with the old build system.
=> cmake: add Makefile to build and run tests from tmp/

src/xlat-i/sdag/CSdagConstruct.C
This issue fixes an error Ajay reported on Slack, in which `ckGetArrayIndex` requires a prefix of `this->` for the code to compile. Reproducible by trying to compile templated SDAG code with `--enable-tracing`, errors take the form:
./data_container.def.h:1075:63: error: use of undeclared identifier 'ckGetArrayIndex'
_TRACE_BEGIN_EXECUTE_DETAILED(-1, -1, _sdagEP, CkMyPe(), 0, ckGetArrayIndex()....
^
./data_container.def.h:1158:92: error: use of undeclared identifier 'ckGetArrayIndex'
...-1, (_sdag_idx_DataContainer_serial_0()), CkMyPe(), 0, ckGetArrayIndex().getProj...
^
data_container.def.h:1229:92: error: use of undeclared identifier 'ckGetArrayIndex'
...-1, (_sdag_idx_DataContainer_serial_1()), CkMyPe(), 0, ckGetArrayIndex().getProj...
^
data_container.def.h:1249:92: error: use of …
=> Fix for SDAG Code with Tracing Enabled

src/arch/util/machine-smp.C
Fixes 1cadca2c05b7eaa6f5339a6a0b5890610bcead6e.
=> Check if __has_include is defined before using it

CMakeLists.txt, buildcmake
=> cmake: add conv-mach-smp for gni/persistent

tests/ampi/privatization/test-f90-tlsglobals.f90, tests/ampi/privatization/test-f90.f90
Prevents #2932 from causing autobuild to fail.
=> AMPI: Temporarily disable formatted print statements in privatization test

CMakeLists.txt, README.charm4py, buildcmake, buildold, src/arch/netlrts/machine.C, src/ck-core/charm++.h, src/ck-core/charm.h, src/ck-core/ck.C, src/ck-core/ckarray.C, src/ck-core/ckarray.h, src/ck-core/ckcallback.C, src/ck-core/ckcallback.h, src/ck-core/cklocation.h, src/ck-core/ckreduction.C, src/ck-core/ckreduction.h, src/ck-core/init.C, src/ck-core/register.C, src/ck-perf/trace-common.C, src/scripts/Makefile, src/scripts/configure.ac, src/util/charmrun-src/charmrun.C
- rename all remaining 'charmpy' references to 'charm4py'
- remove charmpy cmake build option ('charm4py' must be the target)
=> charm4py: cleanups

src/libs/ck-libs/CMakeLists.txt, src/libs/ck-libs/armci/Makefile, src/libs/ck-libs/armci/libmodulearmci.dep
Fixes errors due to not linking with -ltcharm-compat.
=> ARMCI: Add libmodulearmci.dep

CMakeLists.txt
Fixes #2948.
Tested with cmake 3.4, 3.10, 3.11, 3.17.
=> cmake: remove warning regarding CheckIncludeFile

benchmarks/ampi/Makefile, benchmarks/ampi/alltoall/Makefile, benchmarks/ampi/isomalloc/Makefile
It looks like
onesided \
pingpong \
speed \
are designed for 2 PE runs.
=> AMPI Benchmarks: Add a testp target for scalable testing on P pes

.github/workflows/multicore_darwin.yml, CMakeLists.txt
Also tests that the stats files (`.sts`) generated from tracing megatest can be loaded by Projections.
=> ci: add multicore-darwin with tracing test

src/ck-perf/trace-projections.C
e77edeca133aa0c7584a6b89d555cf408abc6887 removed the number of PEs from the `LogEntry::pup` function, which Projections needs to read the logs.
=> Fix projections logs for CREATION_{BCAST, MULTICAST} broken in e77ede

src/libs/ck-libs/amr/bitvec.h
Use placement new to put custom BitVec array index in the index member
of CkArrayIndex.
=> AMR: Fix hashing and update style of custom array index

tests/charm++/varTRAM/Makefile
Related to #2987.
The varTRAM test hangs when PEs are oversubscribed in the UCX build, e.g. 4 PEs on 2 physical cores of GitHub CI.
This is a band-aid solution to avoid oversubscribing which causes the hang, but the test itself and/or TRAM internals should be ultimately fixed to not hang even with oversubscription.
=> TRAM: Change test to use 2 PEs to avoid hang on UCX

src/conv-core/conv-rdma.C
putDataHandler is a converse handler used in the non-onesided version
of CmiIssueRput (i.e. on non-RDMA layers like netlrts). Before this
commit, not freeing the payload message was causing a huge memory leak
while using CmiIssueRput. This bug was noticed in the crashes seen in
the isomalloc tests that use the pup_buffer API.
=> Free received converse message in putDataHandler

relink.script
If one of subdirs was missing, rm would fail to remove any of
them, so now rm each member of subdirs individually.
=> Make relink.script more resilient

src/arch/verbs/machine-ibverbs.C
This code is exercised when sending large messages through the regular API (from LrtsSendFunc)
=> Verbs Machine Layer: Add incorrectly removed rdma ack handling code

examples/charm++/cuda/matmul/matmul.C, examples/charm++/cuda/vecadd/vecadd.C, src/arch/cuda/hybridAPI/README.txt, src/arch/cuda/hybridAPI/hapi.h, src/arch/cuda/hybridAPI/hapi_functions.h, src/arch/cuda/hybridAPI/hapi_impl.cpp
Related to #1505.
`hapiHostMalloc` defined in `hapi.h` does not work properly since it is defined as either `void* hapiPoolMalloc(size_t size)` or `cudaError_t cudaMallocHost(void** ptr, size_t size)` depending on the compile-time flags.
This PR updates `hapiPoolMalloc` to have the same signature as `cudaMallocHost` to resolve this issue.
=> Update hapiPoolMalloc to match signature of cudaMallocHost

benchmarks/ampi/alltoall/mpibench.c
`unistd.h` was required previously and I don't see why it should be included now.
This fixes the windows autobuild issue seen in mpi-win-x86_64{-smp}. 
```
make -C alltoall test OPTS='-optimize -production ' TESTOPTS=''
make[2]: Entering directory '/home/nikhil/autobuild/mpi-win-x86_64/charm/mpi-win-x86_64/benchmarks/ampi/alltoall'
../../../bin/ampicc -c mpibench.c -optimize -production 
mpibench.c
mpibench.c(4): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
Fatal Error by charmc in directory /home/nikhil/autobuild/mpi-win-x86_64/charm/mpi-win-x86_64/benchmarks/ampi/alltoall
```
http://charm.cs.illinois.edu/autobuild/old.2020_08_18__01_05/mpi-win-x86_64.txt
=> Remove unistd.h header file from mpibench.c

CMakeLists.txt, cmake/ci-files.cmake, src/libs/ck-libs/ampi/CMakeLists.txt
Makes build errors such as https://github.com/UIUC-PPL/charm/pull/3024 a bit easier to find and debug.
=> build: make sure we can link executables

examples/collide/collidecharm/Makefile, examples/collide/collidecharm/hello.C, examples/collide/collidethread/hello.C, src/libs/ck-libs/collide/Makefile, src/libs/ck-libs/collide/bbox.h, src/libs/ck-libs/collide/collide_buffers.C, src/libs/ck-libs/collide/collide_buffers.h, src/libs/ck-libs/collide/collide_cfg.h, src/libs/ck-libs/collide/collide_serial.C, src/libs/ck-libs/collide/collide_serial.h, src/libs/ck-libs/collide/collide_util.C, src/libs/ck-libs/collide/collide_util.h, src/libs/ck-libs/collide/collidec.h, src/libs/ck-libs/collide/collidecharm.C, src/libs/ck-libs/collide/collidecharm.ci, src/libs/ck-libs/collide/collidecharm.h, src/libs/ck-libs/collide/collidecharm_impl.h, src/libs/ck-libs/collide/threadCollide.C, src/libs/ck-libs/collide/threadCollide.ci
Ran two vim commands on all files:
1. gg=G (Fix indentation and remove tabs)
2. %s/\s\+$//e (To remove trailing whitespaces)
=> Collision detection library and examples: Formatting/Stylistic cleanup 

src/ck-core/cklocation.C
In cases with frequent load balancing, chains of stale location table entries
can cause messages with extremely high numbers of hops to reach their
destination. This change limits the impact of these chains by routing messages
through the home PE as soon as a potential chain (hops > 2) is detected.
Further work should also go towards clearing out location tables to remove
the existence of these chains entirely.
#2060
=> CkLocMgr: Bound number of hops that messages can take

src/ck-core/ckrdma.C, src/ck-core/ckrdma.h
Previously, the acking scheme was botton-up with intermediate nodes
sending an ack message to their parent nodes when all the nodes below them
had completed performing rgets. With this commit, intermediate nodes
send an ack message to their parent nodes when their immediate child
nodes have completed performing rgets. This makes acking more
optimized resulting in earlier consumption of the intermediate node
message and earlier execution of the root node's callback allowing it to
reuse/free the source buffer pointer at an earlier point in time.
=> Zcpy Bcast API: Implement one-level acking

src/ck-core/ckrdma.C, src/ck-core/ckrdma.h, src/xlat-i/xi-Entry.C
- Removes *forwardMsg parameter from ZC Post version of CkRdmaIssueRgets
- Removes msgSize variable from ZC Post version of CkRdmaIssueRgets
=> ZC Bcast API: Minor Cleanup

build, buildcmake
- No need to run ./build inside charm/
- No need for the --destination dir to be inside charm/
Followup of #3047.
Fixes https://github.com/spack/spack/issues/18460
=> cmake: arbitrary destination and out-of-source build dirs

doc/Makefile
`which -s` is broken, my local version of `which` has no support for the `-s` flag (and I can't find what it's supposed to mean, either). Using the POSIX standard `command` command fixes this for me and will be more compatible in general.
=> Doc: Check for program existence using POSIX standard "command" instead of "which"

CMakeLists.txt
Avoids spurious failures when creating the symlinks
=> cmake: create_symlinks with verbatim command

doc/index.rst
The discourse group has been deactivated for a long time now.
=> change discourse to github discussions

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ampiOneSided.C, src/libs/ck-libs/ampi/ampif.C, src/libs/ck-libs/ampi/ampiimpl.h
- Fix crash when getting builtin attributes from C/C++
- Disallow setting builtin attributes
- Separate Comm, Type, and Win builtin attribute checking
- Consider Win attributes to be per-window instead of per-PE
- Code organization cleanups
=> AMPI: Clean up built-in attributes

src/libs/ck-libs/ampi/Makefile, src/scripts/Makefile
Followup from #2853 
Followup from #2856
=> buildold: Never run autoconf for hwloc or ROMIO

src/libs/ck-libs/ampi/ampi.h, src/libs/ck-libs/ampi/ampi_functions.h
Provided by:
- mpi-io/iread_all.c
- mpi-io/iread_atall.c
- mpi-io/iwrite_all.c
- mpi-io/iwrite_atall.c
- mpi-io/register_datarep.c
=> AMPI: Remove NOIMPL declarations of MPI_File symbols provided by ROMIO

doc/charm++/manual.rst
Documented the limits on the number of outstanding futures per PE. Feel free to make suggestions on language, clarity, etc.
=> Doc: specify maximum allowed number of outstanding futures per PE

src/libs/ck-libs/ampi/romio/README.AMPI, src/libs/ck-libs/ampi/romio/mpi-io/glue/large_count.c
cc https://github.com/spack/spack/issues/18460
=> romio: do not build MPI_Type_size_x and MPI_Status_set_elements_x

src/ck-ldb/LBManager.C, src/ck-ldb/LBManager.h, src/ck-ldb/TreeLB.C, src/ck-ldb/TreeLevel.h, src/ck-ldb/TreeStrategyFactory.h
I'm not 100% sold on using using macros for registration and name printing as done here, but I think it's the only real way to map class names to strings "automatically." I think ideally the strategy classes would register themselves using a `map` in the factory and some static initialization, but that gets a little bit complicated with the templating here.
=> LB #3131: Show pluggable TreeLB strategies in help message

buildcmake, buildold
Fixes a bug where partial rebuilds in tmp/ lacked -build-shared.
Fixes a bug where re-invoking ./buildold with AMPI-only failed.
=> build: Detect repeated invocations and warn users

src/libs/ck-libs/ampi/CMakeLists.txt, src/libs/ck-libs/ampi/Makefile
Fixes warning spam seen with ICC.
=> AMPI: Avoid self-inflicted deprecation warnings when building

examples/charm++/zerocopy/entry_method_post_api/prereg/simpleZeroCopy/simpleZeroCopy.C, examples/charm++/zerocopy/entry_method_post_api/prereg/simpleZeroCopy/simpleZeroCopy.ci, examples/charm++/zerocopy/entry_method_post_api/reg/simpleZeroCopy/simpleZeroCopy.C, examples/charm++/zerocopy/entry_method_post_api/reg/simpleZeroCopy/simpleZeroCopy.ci, examples/charm++/zerocopy/entry_method_post_api/unreg/simpleZeroCopy/simpleZeroCopy.C, examples/charm++/zerocopy/entry_method_post_api/unreg/simpleZeroCopy/simpleZeroCopy.ci
The bug was causing a segfault because of the execution of the POST
entry method before the allocation of the receive buffers. This was
happening because the allocation was not happening in the object's
constructor. The fix involved moving the allocation of receive buffers to the
constructor of the object. This ensures that the buffers are
allocated before the POST entry method executes.
=> Fix rare bug seen in ZC EM Post API examples

src/arch/util/machine-broadcast.C
The bug is seen as a crash on the child node when it tries to forward the
message to its peer PEs after receiving a bcast message forwarded by an
an intermediate root node. The bug was caused by an incorrect CMI_DEST_RANK
and the fix was to reset this on the child node before forwarding it to peers.
=> ZC Bcast API: Fix bug seen in smp mode with 2 level bcast

src/ck-ldb/lbdb.h
Pursuant to P1766R1 <http://wg21.link/p1766r1>, remove typedef name
for linkage on non-C compatible structs.
Clang 11 warns about this, this patch fixes those warnings.
=> LB: Remove typedef for structs in lbdb.h

CMakeLists.txt, cmake/hwloc.cmake, src/libs/ck-libs/ampi/CMakeLists.txt
Fixes "warning: jobserver unavailable: using -j1."
Fixes parallelism of hwloc, ROMIO, and all-test build steps.
=> CMake: Let child Make instances see parent jobserver

cmake/detect-features-cxx.cmake, src/arch/win/unix2nt_cc, src/scripts/configure.ac
Needed to avoid migratable threads failing the stack check.
=> unix2nt_cc: Implement -fno-stack-protector and update comments

.clang-format
Improves readability of nested preprocessor directives. `clang-format` has enough awareness to not apply this to things like include guards.
Changes this:
```
#if FOO
#if BAR
#include <foo>
#endif
#endif
```
to this:
```
#if FOO
#endif
```
=> Update .clang-format: Indent preprocessor directives

src/ck-perf/trace-common.C
In making this patch, I also discovered that we currently have a `gethostname` check in `configure.ac`. I don't think this is really needed (plus, the result `CMK_GET_HOSTNAME` is already not universally used) since both POSIX and Windows guarantee this function exists. Am I missing some reason why we need this check or can it be removed?
=> Tracing: Add hostname to Projections logs

src/ck-core/cklocation.C, src/ck-core/ckmigratable.h, src/ck-core/cksyncbarrier.C, src/ck-core/cksyncbarrier.ci, src/ck-core/cksyncbarrier.h
Fixes race condition where CkMigratable calls AtSync before migrating, causing a hang on destination PE.
=> Migrate AtSync barrier refcount

src/ck-core/charm++.h
I'm not sure where CMK_HAS_RVALUE_REFERENCES was ever defined, grepping through the history only shows this one usage.﻿
=> Use perfect forwarding to pass args to chare's parent constructor

examples/charm++/PUP/STLPUP/SimplePUP.C, examples/charm++/PUP/STLPUP/SimplePUP.ci, examples/charm++/PUP/STLPUP/SimplePUP.h, src/util/pup_stl.h
This patch enables PUP'ing of C++ shared pointers, where previously we could only PUP unique pointers. This limitation seems rather arbitrary to me, given we're on C++11 and should have support for both.
=> Enable PUP'ing of C++ Shared Pointers

buildcmake
Fixes folder not found errors when `--basedir` is passed in.
=> Fix USER_OPTS_LD in conv-mach-pre.sh

src/util/pup.h, src/util/pup_stl.h
This fixes potential invalid frees that can arise when a dynamic cast "changes" the address of the pointer. This _rarely_ occurs, but complex inheritance relationships can lead to these classes of failures (particularly when `PUP::able` is not the last class that a class publicly inherits). To make this possible, the virtual destructor of `PUP::able` needed to be made `public` from `protected`, but this is consistent with `PUP::er` and, since the destructor is a no-op, does not break encapsulation.
=> Fix Potential Invalid Free Due to Dynamic Cast

src/arch/common/cc-icc.sh
Building on Frontera without this patch results in an hwloc configure error:
```
$ ./build charm++ ucx-linux-x86_64 smp icc --with-production --enable-tracing --basedir=$HOME/ucx/build -j16
...
configure: error: unrecognized option: `-fpic'
Try `<...>/ucx-linux-x86_64-smp-icc/hwloc-prefix/src/hwloc/configure --help' for more information
make[2]: *** [hwloc-prefix/src/hwloc-stamp/hwloc-configure] Error 1
```
=> icc: Fix broken hwloc configure

.lgtm.yml
The previous commit excluded `src/libs/ck-libs/metis/GKlib` and other METIS root level files/folders.
=> fixup! CI: Classify external code as "library" for lgtm (#3217)

cmake/ci-files.cmake
Used for passing e.g. `-DFOO=1`.
=> cmake: honor $OPTS for ci files

benchmarks/converse/commbench/Makefile
I've opened a separate issue to look into the performance issue on golub. (https://github.com/UIUC-PPL/charm/issues/3257).
=> Skip commbench on Golub because it times out autobuild run

src/ck-core/cklocation.C, src/ck-core/cklocation.h, src/ck-core/cksyncbarrier.C, src/ck-core/cksyncbarrier.ci, src/ck-core/cksyncbarrier.h, src/ck-ldb/LBDatabase.C
Previously, `CkLocMgr` was shoehorned into being an AtSync client and AtSync would only be called when at least one load balancer existed, this removes these restrictions, allowing AtSync to be cleanly used for non-LB purposes and creating less blurry boundaries between the various components.
New classes of receivers, BeginReceiver and EndReceiver, are added as part of this PR. BeginReceiver and EndReceiver are used for setup and cleanup tasks for regular Receivers, which is where things like LB or other useful work is done. Currently, BeginReceiver and EndReceiver are used in CkLocMgr to trigger RegisteringObjects and DoneRegisteringObjects.
Please rebase as a merge strategy.
Replaces #3247 and #3170, this is a combined version of both of those PRs.
=> Disentangle AtSync-LB-CkLocMgr dependencies

src/libs/ck-libs/cache/CkCache.h
When changa is compiled with COSMO_STATS defined, the compile fails with
```
/home/trq/nchil/src/charm/include/CkCache.h: In member function ‘void CkCacheManager<CkCacheKey>::collectStatistics(CkCallback)’:
/home/trq/nchil/src/charm/include/CkCache.h:615:5: error: there are no arguments to ‘contribute’ that depend on a template parameter, so a declaration of ‘contribute’ must be available [-fpermissive]
615 |     contribute(sizeof(CkCacheStatistics), &cs, CkCacheStatistics::sum, cb);
|     ^~~~~~~~~~
/home/trq/nchil/src/charm/include/CkCache.h:615:5: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
```
This fixes the error.
=> CkCache.h: Fix compile error if COSMO_STATS is defined.

src/ck-core/cklocation.C, src/ck-core/cksyncbarrier.C, src/ck-core/cksyncbarrier.ci, src/ck-core/cksyncbarrier.h, src/ck-core/init.C, src/ck-ldb/LBDatabase.C, src/ck-ldb/LBManager.C, src/ck-ldb/LBManager.h
Fixes stylistic issues, particularly with variable and method names. Additionally, changes the semantics of the kick epoch, previously it would trigger the barrier when it was greater than or equal to the current epoch, now it must be strictly greater than the current epoch to trigger the barrier (which mirrors the behavior of regular AtSync elements).
=> Cleanup CkSyncBarrier code

cmake/converse.cmake, src/ck-core/CMakeLists.txt, src/ck-perf/CMakeLists.txt, src/libs/ck-libs/ampi/CMakeLists.txt
This reverts commit 3cd2c7b17bb4be260d9606ad65b6c9de2a6c3429, which did not actually work, and CI did not catch it.
=> Revert "buildcmake: Use -cpmod to copy Fortran .mod files (#3159)"

benchmarks/converse/commbench/Makefile
The previously seen slowdown in commbench was a result of incorrect
PE-binding caused because of not specifying the number of processes
in the slurm job script. Since it was not a bug within charm, this
commit reverts the skipping of benchmarks/converse/commbench since
it runs without any slowdown when the -n <processes> SBATCH directive
is passed in the slurm script.
=> Do not skip commbench on Golub

src/ck-core/ckarray.C
The function `msg_prepareSend_noinline` is completely unused and serves only as non-inline, outdated/incorrect version of an internal function for whom having a non-inline version has no benefits. Namely, it does not have the updates/later additions of `env->setMsgtype(ForArrayEltMsg);` and `env->setRecipientID(ck::ObjID(0));` found in `msg_prepareSend`, which will cause error-checking failures if it is used instead of its inline counterpart.
I am of the opinion that it should be removed, updated, or made externally available. Perhaps, at one point, it was declared in `ckarray.h` so it was externally available -- but most users (e.g. libraries) that need to prepare a message destined for an array need more customization than this function offers, anyway.
=> Remove Unused Function `msg_prepareSend_noinline`

doc/ampi/04-extensions.rst, tests/ampi/megampi/test.C
Fixes autobuild issue seen on Windows.
=> AMPI: Document that attribute pointers become invalid after migration

.github/workflows/charm4py.yml
Official Python 2 support ended on January 1, 2020 (and that's after a long extension), so I think it's more than fine not to test it or support it anymore.
=> CI: Remove Python 2 test for charm4py

src/arch/verbs/machine-ibverbs.C
Allow `blockAllocRatio` and `blockThreshold` parameters to be specified at runtime.
ChaNGa can use these to change the values and bypass `ibv_reg_mr` errors on machines such as Bridges-2.
=> Support runtime parameters for IB verbs machine layer

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ampiimpl.h
Users can set these at AMPI build time by appending
-DAMPI_MSG_POOL_SIZE_DEFAULT=X -DAMPI_POOLED_MSG_SIZE_DEFAULT=Y
and/or at run time by setting the environment variables AMPI_MSG_POOL_SIZE=X and
AMPI_POOLED_MSG_SIZE=Y, where X is the max number of msgs kept in the pool
and Y is the max number of bytes in a pooled message.
=> AMPI: expose msg pool size parameters to users

CMakeLists.txt, src/scripts/charmc
Fixes #3317.
'-MD' does not take an argument (see https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html)
=> charmc: fix dependency generation with -MD

src/ck-core/cklocation.C, src/ck-core/cklocation.h
This moves pupping of the location table to CkLocCache, where the table is stored. It
also fixes an issue where IDs were being packing but indices were being unpacked.
=> LocMgr: Fix syncft builds

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ampiOneSided.C, src/libs/ck-libs/ampi/ampiimpl.h
- Batch prints on a whole-line basis so that SMP mode runs are legible
- Add dereferencing of pointer parameters
=> AMPI: Improve MPI-level trace printing

src/libs/ck-libs/ampi/Makefile
Fixes 212235404e5ab23f6e28d8233c6302f1ec9073e9
=> AMPI: Fix ROMIO build failure without Fortran

src/util/cklists.h
`sentinel` was being cast from `std::numeric_limits<size_t>::max()` to an `int` and then back to a `size_t`.
=> Fix invalid implicit conversions in CkCompactVec

src/ck-ldb/CentralLB.C, src/ck-ldb/MetisLB.C
The METIS manual says that `adjncy` should be of size `2m` where `m = |E|` and that `adjwgt` can be `NULL` when edges are unweighted (they implicitly are when there are no edges, of course). However, internally when it checks the graph, it accesses element zero of both of these arrays, so they can't actually be `NULL` in practice, so create dummy arrays when there are no elements.
=> LB: Fix MetisLB crash when there are no edges

src/scripts/charmc
- Respect ordering of -L* and -Wl,* relative to library names/paths
- Add support for -L and -l with spaces before the name/path
- Avoid passing ifort's -extend-source option to the linker
=> charmc: Clean up linker argument handling

CMakeLists.txt
=> cmake: enable x86_64 -> i386 cross-compilation

src/libs/ck-libs/ampi/ampi.C, src/libs/ck-libs/ampi/ddt.h
Remove useless debug prints and add more info to DDT ones
=> AMPI: clean up debug print statements

buildcmake
`$@` is affected by the `shift` operations.
Fixes #3353. 
Also fixes find's `-maxdepth` warning.
=> cmake: make sure to pass full args to buildold

src/ck-core/ckarray.C, src/ck-core/ckarray.h, src/ck-core/cklocation.C, src/ck-core/cklocation.ci, src/ck-core/cklocation.h, src/ck-core/ckmemcheckpoint.C, src/libs/ck-libs/NDMeshStreamer/NDMeshStreamer.h
Without ordering location update messages, we can get incorrect entries in the location
tables when old updates arrive after new ones. In some cases this can cause stale cycles
that can trap messages indefinitely.
=> LocMgr: Add epoch to location updates to prevent hangs

src/conv-core/convcore.C
- Adds newline to the message printed by ```CmiDeprecateArgInt``` to match other functions such as ```CmiAbort```.
=> Add newline to output of CmiDeprecateArgInt

src/ck-core/ck.C, src/ck-core/ckarray.C, src/ck-core/ckarray.ci, src/ck-core/ckarray.h, src/ck-core/cklocation.C, src/ck-core/cklocation.h, src/xlat-i/xi-Entry.C, src/xlat-i/xi-Parameter.C, src/xlat-i/xi-Parameter.h
As reported by the SpECTRE team, communication to `[inline]` entry methods was not being added to the comm graph. For some reason, the RTS code explicitly avoided adding this to the comm graph, and a newer optimization that called the target EP directly on the object pointer when it was local without ever going into the RTS code also skipped this step. This change removes the condition excluding remote messages to `[inline]` EPs from having their communication traced and adds an explicit call to record the communication when the `[inline]` EP is directly invoked locally on the object pointer (even though this case doesn't actually involve any communication, it should be in the comm graph so that the LB knows that they are communicating and won't separate them when running communication …
=> Trace communication to inline entry methods for LB

src/xlat-i/xi-Entry.C
This PR resolves issue #3402, removing the relevant parts of Charmxi that generate code that overrides the copy constructor. It eliminates implicit creation of singleton chares via `CProxy_[...]::CProxy_[...]`, forcing users to use `ckNew`. This seems to be an unexamined legacy behavior.
=> Remove Implicit Singleton Chare Creation w/ CProxy

doc/charm++/manual.rst, examples/charm++/array_map/array_map.C, src/ck-core/ckarray.C, src/ck-core/ckarray.ci, src/ck-core/ckarray.h, src/ck-core/ckarrayoptions.C, src/ck-core/cklocation.C
Array maps previously automatically called doneInserting on the array after initial insertion. This occurred even for arrays with 0 elements. For cases where users then did dynamic insertion and called doneInserting themselves, doneInserting was essentially a no-op (with some messaging). This change makes it so doneInserting is only automatically called for arrays with static insertion.
=> CkArray: Fix semantics of initCallback/doneInserting

src/conv-core/convcore.C, src/conv-core/converse.h, src/conv-core/threads.C
This adds a library-accessible function for detecting whether the currently executing thread is the main thread. The motivations for this are two-fold: (a) to determine whether or not the currently executing thread should be suspended, and (b) to determine whether the currently executing entry method is `[threaded]`. For libraries that overload aspects of Charm++'s initialization routines (i.e., group creation), (a) pertains to writing threading-agnostic yield routines like:
```cpp
inline void yield(void) {
auto th = CthSelf();
if (CthIsMainThread(th)) {
CsdScheduler(0);
} else {
CthYield();
}
}
```
While the complex machinations in `convcore.C` suggest that the main thread can be suspended (and that other threads will inherit its role of running the scheduler while it is suspended), I …
=> Add CthIsMainThread to Consolidate Logic

src/ck-core/ckarray.h
This feature's omission is curious. As it stands, users attempting to copy array element proxies may bounce up to `CProxy::CProxy(const CProxy&)`; this can result in surprises, e.g., unexpected delegation. Thus, this PR attempts to make the results more in line with user expectations (i.e., simple/direct copying of the relevant fields).
Motivation:
This was discovered in Hypercomm wherein I attempted to use a copy constructor for both node/group and chare-array elements. This led to strange crashes pertaining to delegation, which I circumvented with the addition of `ckUndelegate`; while this avoided the crashes, doing so has a significant performance impact and is suboptimal from various perspectives. Availability of a copy constructor would resolve [this …
=> Add Copy Constructor to CProxyElement_ArrayBase

src/ck-perf/trace-common.C
Fixes issue introduced in #3225, it used an `#ifdef` where it should have used an `#if`.
=> Tracing: Don't write SMPMODE when not in SMP mode

src/ck-core/init.C
Currently, uncaught C++ exceptions in user code cause the following error message to be created:
```
------------- Processor 6 Exiting: Called CmiAbort ------------
Reason: Unhandled C++ exception in user code.
```
This patch attempts to retrieve the exception that was thrown and includes the result of ```exception.what()```, as shown below:
```
------------- Processor 6 Exiting: Called CmiAbort ------------
Reason: Unhandled C++ exception in user code: vector::_M_default_append.
```
The hope is that this information will be useful in debugging user code (it was useful for me). If the exception cannot be retrieved, the first message above is printed.
Further information about exception_ptr: https://en.cppreference.com/w/cpp/error/exception_ptr
=> Include information about uncaught exceptions in user code

src/conv-core/cputopology.C
- Replaces error-prone locking and improper scheduler driving with well-tested pattern from Isomalloc-Sync
- Replaces bespoke "empty reduction" with CmiBarrier
- Replaces Broadcast with NodeBroadcast and moves send outside of handler
- Replaces unnecessary privatization of Converse handler index variables with CmiAssignOnce
=> Clean up cputopology initialization global communication pattern

src/arch/ofi/machine-onesided.C
This commit fixes the ofi autobuild crashes seen on Stampede2.
Previously, registerDirectMemory was defined to return a fid_mr
struct pointer but did not return any argument. This
caused a mysterious crash with SIGSEGV on Stampede2 with gcc 9.1.0.
This commit changes the return type to void, which is the correct
return type for that function, and this in turn fixes the crash.
=> OFI: Change return type of registerDirectMemory to void

src/libs/ck-libs/ampi/ampi.C
This allows programs that do not include mpi.h before defining `main` to
run successfully with these methods, such as in some configure tests.
It also allows running Fortran programs with these methods without
renaming the `program` statement to `subroutine mpi_main`.
=> AMPI: Try `main` as an entry point with fs/pip/pieglobals

src/conv-core/convcore.C, src/conv-core/converse.h
It is possible for node reduction messages to arrive at the root before
it has completed its own CmiNodeReduce* call. Therefore, lock around
all accesses of _nodereduce_info.
=> Converse: Strengthen locking in node reductions

src/ck-ldb/DistBaseLB.h
With MigrateDone being protected, the DistributedLB strategies can call `lbmgr->Migrate` directly without setting the `migrates_expected` to reduce communication.
The DistributedLB strategies can call `CkWaitQD()` to wait for migrations and follow by  `MigrateDone(1)` to resume clients.
=> Move MigrateDone from private to protected in DistBaseLB

src/xlat-i/xi-Entry.C
This PR fixes the inadvertent change (reversion) to the GPU messaging path in charmxi by PR #3387.
=> Fix charmxi issue with GPU messaging path

src/ck-perf/trace-common.h, src/ck-perf/trace-projections.C, src/ck-perf/trace-projections.h
The crux of this is the change to use a `union` inside `LogEntry`, a lot of the other cleanup is in support of making that change. All in all, this changes the size of a `LogEntry` from 184 bytes to 88 bytes (as measured via `clangd` on x86_64 Linux). We could also change the `std::string` and `std::vector` to their size + pointer equivalents to save an additional 20 bytes (assuming we also start using 64-bit ID, otherwise the ID becomes the size constraint and we'd only save 16 bytes), if we decide the space tradeoff is worth using raw pointers.
=> Tracing: Reduce memory usage in Projections tracing

src/ck-perf/trace-projections.C, src/ck-perf/trace-projections.h
Switches from raw buffer used via `placement new` to a `std::vector` used via `emplace_back`. Performance is probably slightly worse due to overheads, but probably worth it for safety.
=> Tracing: Use vector for Projections LogPool

src/xlat-i/xi-Parameter.C, src/xlat-i/xi-Parameter.h
This code was previously used for non-RDMA layers where they
used a copy based approach at the charmxi level. With PR #3120,
the non-RDMA layers used the zcpy api code path which makes this
code obsolete.
=> Cleanup: Remove unused code from non-RDMA code path

buildcmake, buildold, src/arch/cuda/hybridAPI/hapi_impl.cpp, src/conv-core/convcore.C
Add a build option to let users avoid the per-scheduling-loop overhead
associated with CcdSCHEDLOOP, and make AMPI-only builds use it.
This option combined with CSD_NO_IDLE_TRACING and CSD_NO_PERIODIC
greatly simplify the main scheduling loop, improving microbenchmark perf.
=> Csd: add CSD_NO_SCHEDLOOP build option

CMakeLists.txt
Fixes builds (including PAMILRTS on Summit) from breaking by reverting a change by PR #3511.
Snippet of errors before fix:
```
[100%] Linking CXX executable bin/ckhello
/ccs/home/jchoi/work/charm-shmem/pamilrts-linux-ppc64le-smp/lib/libconverse.a(machine.C.o): In function `CmiNotifyStillIdle(CmiIdleState*)':
machine.C:(.text+0xf4): undefined reference to `PAMI_Context_advance'
/ccs/home/jchoi/work/charm-shmem/pamilrts-linux-ppc64le-smp/lib/libconverse.a(machine.C.o): In function `rzv_pkt_dispatch(void*, void*, void const*, unsigned long, void const*, unsigned long, unsigned int, pami_recv_t*)':
machine.C:(.text+0x1a8): undefined reference to `PAMI_Memregion_create'
machine.C:(.text+0x1ec): undefined reference to `PAMI_Get'
/ccs/home/jchoi/work/charm-shmem/pamilrts-linux-ppc64le-smp/lib/lib …
```
=> Revert change to CMK_SYSLIBS in CMakeLists

CMakeLists.txt, buildcmake, cmake/templates/CharmConfig.cmake.in
This PR adds on two important features:
1. Support for `--install-prefix` to *buildcmake*: The default location is set to `$builddir-install`. The user can set this flag
to install Charm++ in their desired folder.
2. Add _CharmConfig.cmake_ template: This CMake config file is configured by the build system. This file is further installed
with Charm++ along with other install files. Using this config file, any dependant project can use `find_project(Charm)` to
find a valid Charm installation. This file also collects important flags that are set at the time of building Charm++. Using this,
the dependent project can identify if the Charm++ installation can be used for the project. For instance, a Non-SMP project
will require a Non-SMP build of Charm++. Using the flag `CHARM_WITH_SMP`, the …
=> Add support for find_package and --install-prefix to Charm++

cmake/templates/CharmConfig.cmake.in
This PR adds 3 more crucial flags to list of Charm++ related flags in CharmConfig.cmake template. The 3 flags are:
1. CHARM_WITH_NETWORK - Sets up the NETWORK flag from cmake
2. CHARM_WITHT_TARGET - Sets up the TARGET flag from cmake
3. CHARM_WITH_ARCH - Sets up the ARCH flag from cmake
=> Add more cmake flags to CharmConfig.cmake

CMakeLists.txt
The value of `CMAKE_CXX_COMPILER_ID` for Intel oneAPI compilers has changed from `Clang` to `IntelLLVM` as of CMake version 3.20.
=> Support IntelLLVM for ICX builds with CMake version >= 3.20

CMakeLists.txt
The current use of CMK_SYSLIBS doesn't allow multiple values in the standalone build. For example, currently ```zlib``` and ```shmem``` cannot be used together. This patch fixes this issue by correcting the way the variable is accessed in CMake.
=> Allow Multiple System Libraries in Standalone Build

doc/charm++/manual.rst, src/ck-core/ckcallback.h
This allows the manipulation of a group or a nodegroup bcast
callback to a local element callback targeted on the local PE for
a group bcast callback and the local node for a nodegroup bcast
callback.
=> Add functionality to transform a group/nodegroup bcast callback

examples/collide/collidecharm/Makefile, examples/collide/collidecharm/hello.C, examples/collide/collidecharm/hello.ci, src/libs/ck-libs/collide/collidecharm.C, src/libs/ck-libs/collide/collidecharm.ci, src/libs/ck-libs/collide/collidecharm.h, src/libs/ck-libs/collide/collidecharm_impl.h, src/libs/ck-libs/collide/threadCollide.C, src/libs/ck-libs/collide/threadCollide.ci
The current client for the collision detection library combines all collisions to a single list on PE 0 before returning the results to the calling program. This works fine for use cases with few collisions. For use cases with many collisions, a distributed scheme avoids bottlenecks.
=> Collide: Add a distributed client option to the collision detection library

src/arch/mpi/machine.C
The MPI-4.0 standard specifies the "mpi_assert_allow_overtaking" info
which users can pass to a communicator creation call in order to tell the
MPI implementation that they don't need msg ordering.
=> MPI layer: assert that Charm does not require msg ordering

doc/charm++/manual.rst, src/ck-core/charm.h, src/ck-core/ckarray.C, src/ck-core/ckarray.h, src/ck-core/ckcallback.C, src/ck-core/ckcallback.h, src/ck-core/cklocation.h, src/ck-core/register.C, src/ck-core/register.h, src/xlat-i/xi-Entry.C
This PR adds more correctness and customization options for calls to `CkCallback::send`.
Currently, sends to array elements via `CkCallback::send` always use a `CkArray_IfNotThere_buffer` policy. Subsequently, sends to `[createhere]` or `[createhome]` EPs do not trigger demand-creation. This PR adds an `ifNotThere` policy field to `EntryInfo` and sets it using Charmxi; `CkCallback::send` now looks up this information and sets the policy accordingly.
A simple example that would fail is:
https://gist.github.com/jszaday/573276ada1b17258caab568c1aea7463
=> Add options to `CkCallback::send` and fix demand-creation

src/ck-perf/trace-projections.C
The standard doesn't state whether char is signed or unsigned, so if
fgetc returns an EOF (-1), unsigned char platforms will always fail when
comparing to the EOF constant.
=> Cleanup: Use correct return type for fgetc

src/ck-perf/trace.h
Calling these as macros breaks with templated chares/EPs with multiple
template parameters because of how the commas are parsed by the
preprocessor.
=> Tracing: Convert outside facing macros into functions

src/scripts/configure.ac, src/xlat-i/xi-Entry.C
4fd8c4b's use of `nullptr` in charmxi code broke autobuild because the older compilers used don't support C++11 natively without a flag. This PR fixes that for `buildold` by ensuring that `configure` adds the right flag for the native compiler. CMake is a stickier wicket in that it doesn't really have any awareness of the native compiler; I've spent a couple hours trying to find a way around it, but I wasn't able to come up with anything that's not very flaky, so I've just reverted the use of `nullptr` for now to get autobuild working in the meantime (Note that CI uses newer compilers that don't suffer from this, which is how this slipped in in the first place. I've verified that this PR fixes the issue on a lab machine.).
Do you have any ideas on how to address this, @matthiasdiener? I …
=> Mitigate C++11 issues in charmxi

src/arch/mpi/machine.C
Can be enabled via passing "-DMPI_POST_RECV=1" to the compiler.
=> MPI: Allow enabling preposted receives with flag

doc/conf.py
From version 5.0.0, Sphinx now no longer accepts `None` as a language.
=> Doc: Specify docs are in English to Sphinx

src/ck-core/ckarray.C, src/ck-core/ckarray.ci, src/ck-core/ckarray.h, src/ck-core/ckrdma.C, src/ck-core/envelope.h, tests/charm++/load_balancing/Makefile, tests/charm++/load_balancing/periodic_lb_broadcast_test/Makefile, tests/charm++/load_balancing/periodic_lb_broadcast_test/ping.C, tests/charm++/load_balancing/periodic_lb_broadcast_test/ping.ci
Implements in-order delivery for array broadcasts, fixes #3605.
@stwhite91 It seems like AMPI violates the contract to disable anytime migration, namely in the AMPI migration test, migrations were happening concurrently with an array broadcast (which I think was backing an `MPI_Scatter`), so I enabled anytime migration in AMPI in the first patch of this PR, which fixed the failure. Is there some way AMPI can guarantee when migrations/collectives can happen so that we don't have to use anytime migration for it?
@ZwFink One of the delivery pathways for this is specialized for Charm4py; I think my changes are correct, but it'd be good to get some eyes that are experienced with Charm4py on this.
=> Add epochs to array broadcasts

buildcmake, doc/charm++/manual.rst
The `cmake` options are not as well documented as the `build` command. It is helpful to allow users to use the `build` command when cmaking `charm` in different folders by reusing the same source tree.
=> Allow using `buildcmake` in another directory

src/ck-core/ckcheckpoint.C
This is the same as pull #3629, but updated for SMP builds and branched off of main.  Fixes Issue #3628.
=> bdcastRO(): include numZerocopyROops in pup sizer.

.github/workflows/namd.yml
GitHub branch protection rules use the name of the build (`build` in most of our CI cases) to require it to pass before being able to merge a PR. Since NAMD requires a secret token to download it from their Gitlab, it will fail on PRs that are opened from outside PPL. By renaming the NAMD build, it will become optional to pass before it can be merged.
=> Rename NAMD CI so it can be optional

buildcmake
#3626 ordered the check to default to `simplepmi` before the check for using `slurmpmi2` on Cray OFI platforms, meaning that `simplepmi` was used by default on those platforms rather than `slurmpmi2`. Instead, do the check for Cray platforms first, and only use the `simplepmi` default if that fails.
=> Fix default PMI on Cray OFI

src/ck-perf/trace-summaryBOC.h
Fixes bug introduced in 245542a99, the time parameter was not removed from the declaration in the header.
=> Tracing: Remove erroneous parameter in summary data collection function

src/util/pup_stl.h
Diamond inheritance patterns like:
```
PUP::able
/   \
/       \
A      B
\     /
\   /
C
```
Don't work with a `static_cast` (or C-style cast), and need to be resolved dynamically. While a dynamic_cast is slower than a static_cast, this cost is likely completely negligible compared to the data copying and network transfer that serialization needs.
Fixes #3657
=> Use dynamic_cast in unique_ptr serialization

cmake/detect-features.cmake
CMK_LUSTREAPI holds the library argument for linking with the Lustre API, "-llustreapi" when it is detected, otherwise "". Special case the replacement that sets empty variables to 0 so that CMK_LUSTREAPI should remain set to "" when Lustre is not detected, otherwise using -module CkIO causes a spurious attempt to link with "0".
=> CMake: Do not substitute empty CMK_LUSTREAPI with 0

buildcmake
Not quoting can cause the expansion to be matched as a pattern rather
than a literal. Reported by ShellCheck SC2295.
=> CMake: Quote parameter expansion for finding extra opts

doc/charm++/manual.rst, src/langs/sdag/examples/ex0/ex0.sdag, src/langs/sdag/examples/ex1/ex1.sdag, src/langs/sdag/examples/ex2/ex2.sdag, src/langs/sdag/examples/ex3/ex3.sdag, src/langs/sdag/examples/ex4/ex4.sdag, src/langs/sdag/examples/ex5/ex5.sdag, src/langs/sdag/examples/lu/lu.sdag, src/langs/sdag/examples/ring/ring.sdag, src/libs/ck-libs/completion/completion.ci
From @stwhite91's suggestion here: https://github.com/UIUC-PPL/charm/discussions/3682#discussioncomment-4768759. This is the only `.ci` file my grep found that used `atomic`. Are there other examples that use it, @stwhite91?
=> Deprecate "atomic" SDAG keyword

.github/workflows/buildold.yml, .github/workflows/changa.yml, .github/workflows/charm4py.yml, .github/workflows/cuda.yml, .github/workflows/doc.yml, .github/workflows/mpi_linux_smp.yml, .github/workflows/multicore_darwin.yml, .github/workflows/namd.yml, .github/workflows/netlrts_darwin.yml, .github/workflows/netlrts_linux_i386.yml, .github/workflows/shellcheck.yml, .github/workflows/spack.yml, .github/workflows/syncft_mpi.yml, .github/workflows/syncft_netlrts.yml, .github/workflows/ucx.yml, .github/workflows/verbs.yml, .github/workflows/windows.yml
Separately, I've created a request with CircleCI to enable testing the branches created by the merge queue feature (as per https://github.com/community/community/discussions/38199 and https://circleci.com/docs/github-integration/, I've asked them to add `gh\-readonly\-queue.\*` to the allow list for Charm).
_Update: CircleCI support have added support for testing merge queue branches to our account, so it should all be in working order now._
=> CI: Trigger on "merge_group" event to support GitHub merge queues

src/arch/mpi/machine.C, src/conv-core/convcore.C
Enables building with "-DCMK_USE_MPI_ALLOC_MEM=1" to make CmiAlloc use
MPI_Alloc_mem internally, independent of USE_MPI_CTRLMSG_SCHEME.
=> MPI layer: add build-time option to use MPI_Alloc_mem inside CmiAlloc

src/arch/verbs/machine-ibud.C, src/arch/verbs/machine-ibverbs.C, src/ck-core/envelope.h, src/conv-core/cmishmem.h, src/conv-core/convcore.C, src/conv-core/converse.h, tests/charm++/alignment/alignmentCheck.C
Use alignas instead of error-prone explicit padding with char[].
=> Converse: Fix and cleanup padding

src/conv-core/CMakeLists.txt
=> CMake: Condition memory-hooks-charmdebug on CMK_HAS_MALLOC_HOOK

buildcmake
fixes `buildcmake: line 583: !option: unbound variable` when building with `-v`.
=> build: fix option printing unset variable

src/conv-core/conv-conds.C, src/conv-core/converse.h, tests/charm++/Makefile, tests/charm++/periodic/Makefile, tests/charm++/periodic/periodic.C, tests/charm++/periodic/periodic.ci
Fix support for timer-based conditional callbacks that was broken by PR #3537,
while still minimizing timer calls when possible.
Also add a test for timer-based conditional callbacks.
=> CcdCallbacks: manage timer-based cond callbacks properly

src/util/ckhashtable.h
The following use of class template fails to build when using GCC 13.1 with --std=c++20:
```
template <typename T>
class Foo {
public:
Foo<T>() {}
};
```
The extra "<T>" in the constructor should be removed for compilation. NAMD uses `CkHashtableAdaptorT` so I need to remove the redundant `<T>` to make it compiled.
=> Fix FTBFS of NAMD when using GCC 13.1 with --std=c++20

src/conv-core/conv-conds.C, src/conv-core/converse.h, tests/charm++/varTRAM/vartest.C, tests/charm++/varTRAM/vartest.ci
*Original date: 2019-04-26 04:00:57*
*Original PR: https://charm.cs.illinois.edu/gerrit/4932*
---
Change-Id: Ie533057d1dba8db277388affce245dc8d2cb50e6
=> Cleanup #1982: Use C++ STL data structures in conv-conds

src/arch/netlrts/machine-persistent.C, src/arch/verbs/machine-persistent.C
Merging #3733 exposed some kind of bug in the Verbs layer causing many tests to fail during autobuild, all in the same way.
Verbs non-SMP: `Fatal error on PE 0> [0] Assertion "startNode >=0 && startNode<_Cmi_numpes" failed in file src/arch/util/machine-broadcast.C line 141`
Verbs SMP: `Fatal error on PE 2> [2] Assertion "((CmiMsgHeaderBasic *)msg)->rank==0" failed in file src/arch/util/machine-broadcast.C line 66`
=> Verbs: Fix CMI_DEST_RANK_NET macro

src/scripts/charmc
Allows specifying (e.g.) -std=c++14 meaningfully
=> charmc: allow extra options to override standard options

src/arch/netlrts/machine-dgram.C, src/arch/netlrts/machine-eth.C, src/arch/netlrts/machine-tcp.C, src/arch/pami/conv-common.h, src/arch/pamilrts/conv-common.h, src/arch/verbs/conv-common.h, src/arch/verbs/conv-mach-syncft.h, src/arch/verbs/machine-dgram.C, src/arch/verbs/machine-ibverbs.C
After examining the runtime issues experienced with the Verbs layer after #3733, and replicating them with NetLRTS by applying the same change to its headers, I believe it is best to revert the change for now, just for Verbs, because fixing the root of the issue will involve deeper cleanup of NetLRTS and Verbs, which is not worth holding up a release.
=> Revert Verbs message header padding change

src/arch/cuda/hybridAPI/hapi_impl.cpp
=> hapiMapping(): handle PEs not a multiple of GPUs.

src/arch/cuda/hybridAPI/hapi_impl.cpp, src/arch/cuda/hybridAPI/hapi_impl.h
=> HAPI createPool() and releasePool(): save chunk addresses for cudaFreeHost()

src/libs/ck-libs/io/ckio.C
This prevents springCleaning on the WriteSession array, and works around possible problems after the array gets deleted.
This works around the springCleaning problem reported in #3762.
It may also fix #3678, but testing this is still in progress.
=> ckio: set AnytimeMigration to false for WriteSession

.readthedocs.yaml, doc/requirements.txt
RTD recently started requiring this file: https://blog.readthedocs.com/migrate-configuration-v2/
=> add .readthedocs.yaml

src/arch/ucx/charmrun
detect that the run is within a SLURM allocation 
if so, use srun as the launcher
choose cray-shasta if craype
This change enables the usual "make test" approach because that relies on testrun, which relies on charmrun.
=> UCX charmrun should use srun --mpi=pmi2 in a SLURM allocation

.github/workflows/ci.yaml, src/ck-ldb/LBManager.h, src/ck-ldb/TreeLB.C
I was testing some charm4py examples and noticing segfaults in `TreeLB::loadConfigFile(CkLBOptions const&)`.
Possibly due to the invalid `const char *`-pupping of `legacyName` in `CkLBOptions`:
```
// used in constructor of all load balancers
class CkLBOptions
{
private:
int seqno;  // for centralized lb, the seqno
const char* legacyName;
public:
CkLBOptions() : seqno(-1), legacyName(nullptr) {}
CkLBOptions(int s) : seqno(s), legacyName(nullptr) {}
CkLBOptions(int s, const char* legacyName) : seqno(s), legacyName(legacyName) {}
int getSeqNo() const { return seqno; }
const char* getLegacyName() const { return legacyName; }
};
PUPbytes(CkLBOptions)
```
A proposed fix in this PR
=> LB: fix pup of CkLBOptions class

.github/workflows/ci.yaml
In preparation for the next release, NAMD's default branch (main) has updated to using namd3.  So our test had to be updated to call namd3 instead of namd2.
=> bugfix: update namd binary from namd2 to namd3

doc/libraries/manual.rst, src/libs/ck-libs/io/ckio.h
Adding CkIO Input documentation to the Charm++ readthedocs and updating relevant comments to address #1521 . This should be basically complete for the current status of CkIO in main. Mat implemented a FileReader streaming abstraction as well (not merged yet) - should that be merged in for this release? In this case, we should add these docs.
=> CkIO documentation and cleanup

.github/workflows/ci.yaml
`macos-latest` is now referring to Mac M1, not x86_64, so we need to use an older version to build for x86_64.
=> fix Mac CI

CHANGES, LICENSE, NOTICE
(per our email discussion)
Same could be done for charm4py, projections, ...
=> Change license to Apache-2.0 with LLVM exceptions

examples/charm++/whenidle/idlework.C, src/xlat-i/xi-Entry.C
Intended to fix issue #3819, allowing for a correct translation of the attributes of an entry method with the whenidle attribute.
=> delete time attribute from whenidle entry method

CMakeLists.txt, src/scripts/configure.ac
Update internal versioning to 8.0.1 for development
=> cleanup: bump version for devel to 8.0.1

doc/charisma/manual.rst, doc/charm++/manual.rst, examples/charm++/Molecular2D/Compute.C, examples/charm++/Molecular2D/Compute.h, examples/charm++/Molecular2D/Patch.C, examples/charm++/Molecular2D/Patch.ci, examples/charm++/Molecular2D/Patch.h, examples/charm++/Molecular2D/common.h
Uses std::vector in place of CkVec in the Molecular2D example, fixes the bug (#3834) in the compilation of Molecular2D by using const references in the method parameters of updateParticles and updateForces, and updates the documentation to clarify how pup_stl.h should be used.
=> Molecular2D example switch from CkVec to std::vector

tests/charm++/periodic/periodic.C
In order to get recent failing test cases to pass so we can merge PRs, I changed the periodic test to use CcdCallFnAfter, not CcdCallOnConditionKeep, which means the test will pass regardless of the value of CkWallTimer in the mainchare of periodic.C.
=> Use CallFnAfter instead of CallOnConditionKeep

.github/workflows/ci.yaml
Fixing spack ci build's clone command to match the charm repo name in spack package. This should fix the spack build error in #3874.
=> Fix ci for spack build

.github/workflows/ci.yaml
The old deploy token expired.
This one uses two repo secrets, one for the username, another for the password token
=> bugfix: update NAMD deploy token

CMakeLists.txt
CMake 4.0 now throws an error if the minimum specified version is below 3.5, so this updates the version.
=> cmake min to 3.12

.github/workflows/ci.yaml, src/conv-ccs/conv-ccs.C, src/conv-ccs/conv-ccs.h, src/conv-core/conv-header.h, src/conv-core/convcore.C
This exposes CCS methods to Cython to allow Charm4Py programs to be used as CCS servers.
=> CCS communication support for charm4py

doc/charm++/manual.rst
This just adds a section each in groups and node-groups in charm++ docs to make reduction on groups easier to locate.
=> added sections on reduction in groups and node-groups

src/ck-ldb/CentralLB.C
Hello,
I want to compile Charm++ with the shrink-expand feature as suggested in the [guide](https://charm.readthedocs.io/en/latest/charm++/manual.html#malleability-shrink-expand-number-of-processors):
```
./build charm++ netlrts-linux-x86_64 --enable-shrinkexpand
```
I encountered the following compilation error:
```
...
/home/tan/master/thesis/opt/charm/src/ck-ldb/CentralLB.C: In member function ‘void CentralLB::ResumeFromReallocCheckpoint()’:
/home/tan/master/thesis/opt/charm/src/ck-ldb/CentralLB.C:1073:45: error: request for member ‘begin’ in ‘se_avail_vector’, which is of non-class type ‘char*’
1073 |     std::vector<char> avail(se_avail_vector.begin(), se_avail_vector.begin() + CkNumPes());
|                                             ^~~~~ …
```
=> Fix --enable-shrinkexpand build 

.github/workflows/ci.yaml
2 weeks ago, Spack changed its directory structure, causing our spack_ubuntu-latest test to fail. This fixes that in ci.yaml.
=> fix spack directory

.github/workflows/ci.yaml, CMakeLists.txt, buildcmake, cmake/converse.cmake, cmake/fetch_reconverse/CMakeLists.txt
Changes in this PR include
- Enable cmake autofetch for reconverse: no need to download the reconverse source code.
- Build reconverse as a shared library: no need to specify all its dependencies inside `charmc`.
~~- Comment out `CmiCheckAffinity` for now.~~ (https://github.com/charmplusplus/reconverse/pull/93 fixes it.)
- Add more arguments to the `build` script, including
- `--with-fetch-reconverse-tag`: git tag/hash to fetch reconverse (default option: `main`)
- `--wtih-fetch-reconverse-dir`: path to local reconverse source code (default option: none). If specified, charm will not download reconverse from GitHub but use the local copy.
- `--with-cmake-args`: additional cmake variables to pass.
- `--without-reconverse-fetch-lci`: if you don't want reconverse to fetch lci automatically …
=> improve cmake support for charm on top of reconverse 

src/libs/ck-libs/allGather/allGather.C
also, msvc doesn't recognize "and" as an alias for &&
=> bugfix: for WIN32 compatibility, getpid needs include process.h

src/conv-core/shmem/cmishmem.C
Changes to the definition of CmiAssertMsg means that if you pass --enable-shmem as a build option, the build will fail because 2 calls to CmiAssertMsg in cmishmem.C don't actually have error messages. This fixes this by turning those calls into regular CmiAssert calls.
=> bugfix: Fix SHMEM build error by fixing CmiAssert calls
